In [20]:
from torch.utils.data import Dataset, DataLoader
import torch
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans, HDBSCAN
# GaussianMixture
from sklearn.mixture import GaussianMixture

import matplotlib.pyplot as plt
import yfinance as yf
import seaborn as sns
# import
from hmmlearn.hmm import GaussianHMM
import pickle

In [21]:
device ="mps"

In [22]:
with open('../../data/complete_features.pkl', 'rb') as f:
    all_data = pickle.load(f)

In [23]:
data = all_data["scaled_featured"].copy()

In [24]:
data

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20
Date,,,,,,,,,,,,
2008-07-07,-1.220376,-1.882225,2.081321,-0.864592,-1.135796,-0.628471,-0.569023,-2.119483,1.416877,0.823997,-2.165333,-0.568676
2008-07-08,-1.211754,-1.882225,2.077736,-0.022097,-1.117078,-1.046961,-0.542321,-2.455523,1.450259,0.981827,-2.206775,-0.513460
2008-07-09,-0.957426,-1.882225,2.289506,1.636228,-1.218247,-0.338846,-0.561373,-1.988903,1.476862,0.785786,-1.960992,-0.565134
2008-07-10,-0.975703,-1.882225,2.287995,-0.006124,-1.013921,-0.474801,-0.596656,-2.401313,1.493754,0.505013,-1.940271,-0.562557
2008-07-11,-1.136144,-1.882225,2.391761,0.804554,-1.050675,-0.396400,-0.475448,-2.987661,1.507027,0.400347,-2.078101,-0.510752
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-15,0.375855,0.654743,-0.795604,0.021503,0.541634,-0.126723,-0.727148,-1.189892,-0.988672,-0.309058,0.314003,0.507783
2025-09-16,0.280399,0.654743,-0.833663,-0.287568,0.045456,-0.238463,-0.708679,-1.276291,-1.000565,-0.327333,0.453848,0.513354
2025-09-17,0.260114,0.654743,-0.836851,-0.019044,0.154682,-0.363408,-0.703390,-1.335486,-1.009414,-0.239281,0.522324,0.511624
2025-09-18,0.293060,0.654743,-0.832619,0.038097,0.230366,-0.508229,-0.737254,-1.044970,-1.020331,-0.299090,0.591810,0.309460
2025-09-19,0.080198,0.654743,-0.823297,0.077298,0.164701,-0.717435,-0.742174,-1.146226,-1.028834,-0.229313,0.500421,0.283359

In [25]:
close = all_data["Close"].copy()
close

Date
2008-07-07     4030.000000
2008-07-08     3988.550049
2008-07-09     4157.100098
2008-07-10     4162.200195
2008-07-11     4049.000000
                  ...
2025-09-15    25069.199219
2025-09-16    25239.099609
2025-09-17    25330.250000
2025-09-18    25423.599609
2025-09-19    25327.050781
Name: Close, Length: 4219, dtype: float64

In [26]:
data.shape

(4219, 12)

In [27]:
class TimeSeriesWindowDataset(Dataset):
    def __init__(self, data, window_size=60):
        """
        data: numpy array [T, D]
        """
        self.data = torch.tensor(data, dtype=torch.float32)
        self.window_size = window_size

    def __len__(self):
        return len(self.data) - self.window_size + 1

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.window_size]
        return x

window_size = 60
val_size = 0.2

train_size = int(len(data) * (1 - val_size))
train_data = data.iloc[:train_size]
val_data = data.iloc[train_size:]

train_dataset = TimeSeriesWindowDataset(train_data.values, window_size)
val_dataset = TimeSeriesWindowDataset(val_data.values, window_size)
combined_dataset = TimeSeriesWindowDataset(data.values, window_size)

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
combined_loader = DataLoader(combined_dataset, batch_size=batch_size, shuffle=False)

In [28]:
len(combined_dataset)

4160

In [29]:
for batch in train_loader:
    print(batch.shape)  # Should print torch.Size([32, 60, D])
    break

torch.Size([32, 60, 12])

In [30]:
import torch.nn as nn
import torch.nn.functional as F

class TS2VecModel(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, num_layers=5):
        super(TS2VecModel, self).__init__()
        layers = []
        for i in range(num_layers):
            dilation = 2 ** i
            layers.append(nn.Conv1d(input_dim if i == 0 else hidden_dim, hidden_dim, kernel_size=3, padding=dilation, dilation=dilation))
            layers.append(nn.ReLU())
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        # x: [B, T, D]
        x = x.permute(0, 2, 1)  # [B, D, T]
        x = self.network(x)     # [B, H, T]
        x = x.permute(0, 2, 1)  # [B, T, H]
        # normalize
        x = F.normalize(x, p=2, dim=-1)
        return x

In [31]:
data.shape

(4219, 12)

In [32]:
model = TS2VecModel(input_dim=data.shape[1], hidden_dim=128, num_layers=6).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [33]:
model

TS2VecModel(
  (network): Sequential(
    (0): Conv1d(12, 128, kernel_size=(3,), stride=(1,), padding=(1,))
    (1): ReLU()
    (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
    (3): ReLU()
    (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
    (5): ReLU()
    (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
    (7): ReLU()
    (8): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(16,), dilation=(16,))
    (9): ReLU()
    (10): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(32,), dilation=(32,))
    (11): ReLU()
  )
)

In [34]:
def time_mask(x, mask_ratio=0.2):
    B, T, D = x.shape
    mask_len = int(T * mask_ratio)
    start = np.random.randint(0, T - mask_len)
    x = x.clone()
    x[:, start:start+mask_len, :] = 0
    return x


def jitter(x, sigma=0.02):
    return x + sigma * torch.randn_like(x)


def temporal_pooling(z):
    if z.size(1) % 2 == 1:
        z = z[:, :-1]
    return z.reshape(z.size(0), z.size(1)//2, 2, z.size(2)).mean(dim=2)


def ts2vec_contrastive_loss_vectorized(
    z1, z2,
    temperature=0.1,
    base_exclusion_radius=5
):
    """
    z1, z2: [B, T, C]
    """
    B, T, C = z1.shape
    device = z1.device

    # flatten (instance, time)
    z1_flat = z1.reshape(B*T, C)
    z2_flat = z2.reshape(B*T, C)

    # cosine similarity == dot product because embeddings are normalized
    sim = torch.matmul(z1_flat, z2_flat.T) / temperature   # [BT, BT]

    # ----- temporal negative mask -----
    exclusion_radius = min(base_exclusion_radius, (T - 1) // 2)

    if exclusion_radius == 0:
        return torch.tensor(0.0, device=device)

    # time index per row
    time_idx = torch.arange(T, device=device).repeat(B)     # [BT]

    # batch index per row
    batch_idx = torch.arange(B, device=device).repeat_interleave(T)

    # same batch & temporally close → mask out
    temporal_dist = torch.abs(time_idx[:, None] - time_idx[None, :])
    same_batch = batch_idx[:, None] == batch_idx[None, :]

    invalid_negatives = same_batch & (temporal_dist <= exclusion_radius)

    # allow diagonal (positive pairs)
    diag = torch.eye(B*T, device=device, dtype=torch.bool)
    invalid_negatives = invalid_negatives & (~diag)

    # mask invalid negatives
    sim = sim.masked_fill(invalid_negatives, -1e9)

    # positives are diagonal
    labels = torch.arange(B*T, device=device)

    return F.cross_entropy(sim, labels)



def hierarchical_ts2vec_loss_v2(
    z1, z2,
    temperature=0.1,
    exclusion_radius=5,
    min_time=2
):
    total_loss = 0.0
    depth = 0

    while z1.size(1) >= min_time:
        T = z1.size(1)

        if T > 2 * exclusion_radius + 1:
            total_loss += ts2vec_contrastive_loss_vectorized(
                z1, z2,
                temperature,
                exclusion_radius
            )
            depth += 1

        z1 = temporal_pooling(z1)
        z2 = temporal_pooling(z2)

    return total_loss / max(depth, 1)

In [36]:
%%time
for epoch in range(3):
    total_loss = 0
    model.train()
    for x in train_loader:
        x=x.to(device)
        x1 = jitter(time_mask(x))
        x2 = jitter(time_mask(x))
        z1 = model(x1)
        z2 = model(x2)


        loss = hierarchical_ts2vec_loss_v2(z1, z2)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        # print(f"Batch Loss: {loss.item():.4f}")
    # model.eval()
    # with torch.no_grad():
    #     val_loss = 0
    #     for x in val_loader:
    #         x = x.to(device)
    #         x1 = jitter(time_mask(x))
    #         x2 = jitter(time_mask(x))
    #         z1 = model(x1)
    #         z2 = model(x2)
    #         val_loss += hierarchical_ts2vec_loss_v2(z1, z2).item()

    # val_loss /= len(val_loader)

    print(f"Epoch {epoch}, Loss {total_loss / len(train_loader):.4f}")

Epoch 0, Loss 1.6901
Epoch 1, Loss 0.6712
Epoch 2, Loss 0.5300
CPU times: user 2.67 s, sys: 571 ms, total: 3.24 s
Wall time: 2.77 s

In [159]:
# save model
# torch.save(model.state_dict(), './../../models/ts2vec_nifty.pth')

In [35]:
# load model
# model.load_state_dict(torch.load('../../models/ts2vec_nifty.pth'))

In [37]:
# use full dataset to get embeddings without dataloader
model.eval()
with torch.no_grad():
    full_data_tensor = torch.tensor(data.values, dtype=torch.float32).unsqueeze(0).to(device)  # [1, T, D]
    z=model(full_data_tensor).squeeze(0).cpu().numpy()

In [41]:
temporal_contrast_score_multi(z)

0.68542373

In [161]:
all_embeddings = []
with torch.inference_mode():
    for x in combined_loader:
        # print("x.shape", x.shape)
        x = x.to(device)    
        z = model(x)          # [B, T, C]
        z_mean = z.mean(dim=1)  # [B, C]
        all_embeddings.append(z_mean)

embeddings_full = torch.cat(all_embeddings).cpu().numpy()

In [162]:
len(embeddings_full), len(data) # 4219

(4160, 4219)

In [163]:
val_df = pd.DataFrame(
    embeddings_full,
    index=data.index[window_size - 1:]
)

In [164]:
# val_df["Close"] = all_data["Close"].iloc[window_size-1:].values

In [165]:
val_df.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,127
Date,,,,,,,,,,,,,,,,,,,,,
2008-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000035,0.0,0.000000,...,0.215032,0.000000,0.0,0.0,0.104896,0.0,0.0,0.071229,0.0,0.040119
2008-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000174,0.0,0.000000,...,0.206248,0.000000,0.0,0.0,0.104896,0.0,0.0,0.073362,0.0,0.044781
2008-10-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000233,0.0,0.000124,...,0.198753,0.001280,0.0,0.0,0.104896,0.0,0.0,0.075323,0.0,0.049510
2008-10-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000672,0.0,0.000035,...,0.191434,0.003058,0.0,0.0,0.104896,0.0,0.0,0.076693,0.0,0.056227
2008-10-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000484,0.0,0.000000,...,0.183625,0.004119,0.0,0.0,0.104896,0.0,0.0,0.076525,0.0,0.062015

In [40]:
def temporal_contrast_score(Z, k=20):
    """
    This function computes the temporal contrast score for a given set of embeddings Z.
    Z: [T, C] numpy array of embeddings
    k: temporal gap for negative pairs
    """
    pos = []
    neg = []
    
    for i in range(len(Z) - k - 1):
        pos.append(np.dot(Z[i], Z[i+1]))
        neg.append(np.dot(Z[i], Z[i+k]))
    
    return np.mean(pos) - np.mean(neg)

# score = temporal_contrast_score(embeddings_full)
def temporal_contrast_score_multi(Z, pos_gap=1, neg_gaps=(10,20,40)):
    pos = []
    neg = []

    for i in range(len(Z) - max(neg_gaps) - 1):
        pos.append(np.dot(Z[i], Z[i+pos_gap]))
        for k in neg_gaps:
            neg.append(np.dot(Z[i], Z[i+k]))

    return np.mean(pos) - np.mean(neg)

In [142]:
score

0.077012636

In [17]:
from dataclasses import dataclass

@dataclass
class WindowParams:
    window_size: int

@dataclass
class ArchitectureParams:
    hidden_dim: int
    num_layers: int

@dataclass
class ContrastiveParams:
    temperature: float
    exclusion_radius: int

@dataclass
class AugmentationParams:
    mask_ratio: float
    jitter_sigma: float

@dataclass
class OptimizationParams:
    learning_rate: float
    batch_size: int

In [53]:
import optuna
import torch
import numpy as np

class BaseTS2VecObjective:
    def __init__(self, data, device, fixed_params):
        self.data = data
        self.device = device
        self.fixed_params = fixed_params  # dict of params from previous stages

    def build_model(self, arch_params):
        return TS2VecModel(
            input_dim=self.data.shape[1],
            hidden_dim=arch_params.hidden_dim,
            num_layers=arch_params.num_layers
        ).to(self.device)

    def compute_score(self, model):
        model.eval()
        with torch.no_grad():
            full_tensor = torch.tensor(self.data.values, dtype=torch.float32).unsqueeze(0).to(self.device)
            z = model(full_tensor).squeeze(0).cpu().numpy()
            return temporal_contrast_score_multi(z)

    def train_model(self, model, train_loader, contrastive_params, aug_params, opt_params):
        optimizer = torch.optim.Adam(model.parameters(), lr=opt_params.learning_rate)

        model.train()
        for _ in range(3):  # small epochs for HPO
            for x in train_loader:
                x = x.to(self.device)
                x1 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)
                x2 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)

                z1 = model(x1)
                z2 = model(x2)

                loss = hierarchical_ts2vec_loss_v2(
                    z1, z2,
                    temperature=contrastive_params.temperature,
                    exclusion_radius=contrastive_params.exclusion_radius
                )

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

In [54]:
def create_loader(data, window_size, batch_size):
    dataset = TimeSeriesWindowDataset(data.values, window_size)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [58]:

class WindowStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):
        window_size = trial.suggest_int("window_size", 30, 180, step=30)

        window_params = WindowParams(window_size)

        train_loader = create_loader(self.data, window_size, batch_size=64)

        # fixed architecture for stage 0
        arch_params = ArchitectureParams(hidden_dim=128, num_layers=5)
        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("window_params", window_params.__dict__)

        return score

In [56]:
type(data.values)

numpy.ndarray

In [59]:
study_window = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="window_stage",
    load_if_exists=True
)

# suggest optimal trail count based on combination of parameters 


study_window.optimize(WindowStageObjective(data, device, {}), n_trials=7)

[I 2026-02-22 13:31:11,194] A new study created in RDB with name: window_stage
[I 2026-02-22 13:31:18,083] Trial 0 finished with value: 0.7937400937080383 and parameters: {'window_size': 120}. Best is trial 0 with value: 0.7937400937080383.
[I 2026-02-22 13:31:20,125] Trial 1 finished with value: 0.7081829309463501 and parameters: {'window_size': 60}. Best is trial 0 with value: 0.7937400937080383.
[I 2026-02-22 13:31:26,900] Trial 2 finished with value: 0.7790645360946655 and parameters: {'window_size': 120}. Best is trial 0 with value: 0.7937400937080383.
[I 2026-02-22 13:31:41,269] Trial 3 finished with value: 0.8101174235343933 and parameters: {'window_size': 180}. Best is trial 3 with value: 0.8101174235343933.
[I 2026-02-22 13:31:48,103] Trial 4 finished with value: 0.7787735462188721 and parameters: {'window_size': 120}. Best is trial 3 with value: 0.8101174235343933.
[I 2026-02-22 13:31:50,187] Trial 5 finished with value: 0.7155215740203857 and parameters: {'window_size': 60}. Best is trial 3 with value: 0.8101174235343933.
[I 2026-02-22 13:31:51,689] Trial 6 finished with value: 0.6868016719818115 and parameters: {'window_size': 30}. Best is trial 3 with value: 0.8101174235343933.

In [60]:
class ArchitectureStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        hidden_dim = trial.suggest_categorical("hidden_dim", [64, 128, 256])
        num_layers = trial.suggest_int("num_layers", 3, 7)

        arch_params = ArchitectureParams(hidden_dim, num_layers)

        window_size = self.fixed_params["window_size"]

        train_loader = create_loader(self.data, window_size, batch_size=64)

        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("arch_params", arch_params.__dict__)

        return score
    
study_arch = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="arch_stage",
    load_if_exists=True
)

# suggest n_trials count based on number of combinations (3 hidden_dim options * 5 num_layers options = 15 combinations => suggest 30 trials to cover each combination at least twice)
n_trials = 30

study_arch.optimize(ArchitectureStageObjective(data, device, study_window.best_trial.user_attrs["window_params"]), n_trials= 30)

[I 2026-02-22 13:32:15,033] A new study created in RDB with name: arch_stage
[I 2026-02-22 13:32:34,677] Trial 0 finished with value: 0.7654034495353699 and parameters: {'hidden_dim': 256, 'num_layers': 7}. Best is trial 0 with value: 0.7654034495353699.
[I 2026-02-22 13:32:54,014] Trial 1 finished with value: 0.781647801399231 and parameters: {'hidden_dim': 256, 'num_layers': 7}. Best is trial 1 with value: 0.781647801399231.
[I 2026-02-22 13:33:08,328] Trial 2 finished with value: 0.7660345435142517 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 1 with value: 0.781647801399231.
[I 2026-02-22 13:33:22,557] Trial 3 finished with value: 0.737932562828064 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 1 with value: 0.781647801399231.
[I 2026-02-22 13:33:35,746] Trial 4 finished with value: 0.7127401828765869 and parameters: {'hidden_dim': 64, 'num_layers': 4}. Best is trial 1 with value: 0.781647801399231.
[I 2026-02-22 13:33:50,204] Trial 5 finished with value: 0.7822506427764893 and parameters: {'hidden_dim': 128, 'num_layers': 4}. Best is trial 5 with value: 0.7822506427764893.
[I 2026-02-22 13:34:08,472] Trial 6 finished with value: 0.7559175491333008 and parameters: {'hidden_dim': 256, 'num_layers': 3}. Best is trial 5 with value: 0.7822506427764893.
[I 2026-02-22 13:34:22,472] Trial 7 finished with value: 0.6403794884681702 and parameters: {'hidden_dim': 64, 'num_layers': 7}. Best is trial 5 with value: 0.7822506427764893.
[I 2026-02-22 13:34:38,530] Trial 8 finished with value: 0.7715347409248352 and parameters: {'hidden_dim': 128, 'num_layers': 4}. Best is trial 5 with value: 0.7822506427764893.
[I 2026-02-22 13:34:54,430] Trial 9 finished with value: 0.7386327981948853 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 5 with value: 0.7822506427764893.
[I 2026-02-22 13:35:10,590] Trial 10 finished with value: 0.8008744716644287 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:35:26,541] Trial 11 finished with value: 0.7932373285293579 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:35:42,377] Trial 12 finished with value: 0.7285986542701721 and parameters: {'hidden_dim': 128, 'num_layers': 6}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:35:57,733] Trial 13 finished with value: 0.7935621738433838 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:36:12,889] Trial 14 finished with value: 0.7996993064880371 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:36:26,184] Trial 15 finished with value: 0.6278129816055298 and parameters: {'hidden_dim': 64, 'num_layers': 6}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:36:41,298] Trial 16 finished with value: 0.7418113946914673 and parameters: {'hidden_dim': 128, 'num_layers': 6}. Best is trial 10 with value: 0.8008744716644287.
[I 2026-02-22 13:36:56,104] Trial 17 finished with value: 0.8008858561515808 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 17 with value: 0.8008858561515808.
[I 2026-02-22 13:37:15,683] Trial 18 finished with value: 0.7968429327011108 and parameters: {'hidden_dim': 256, 'num_layers': 6}. Best is trial 17 with value: 0.8008858561515808.
[I 2026-02-22 13:37:28,551] Trial 19 finished with value: 0.698525071144104 and parameters: {'hidden_dim': 64, 'num_layers': 4}. Best is trial 17 with value: 0.8008858561515808.
[I 2026-02-22 13:37:43,212] Trial 20 finished with value: 0.7999460101127625 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 17 with value: 0.8008858561515808.
[I 2026-02-22 13:37:57,829] Trial 21 finished with value: 0.7864035367965698 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 17 with value: 0.8008858561515808.
[I 2026-02-22 13:38:12,442] Trial 22 finished with value: 0.8083674311637878 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:38:27,019] Trial 23 finished with value: 0.7989131212234497 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:38:41,816] Trial 24 finished with value: 0.744179368019104 and parameters: {'hidden_dim': 128, 'num_layers': 6}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:38:56,179] Trial 25 finished with value: 0.7833169102668762 and parameters: {'hidden_dim': 128, 'num_layers': 4}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:39:10,715] Trial 26 finished with value: 0.8032008409500122 and parameters: {'hidden_dim': 128, 'num_layers': 5}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:39:25,418] Trial 27 finished with value: 0.7452600002288818 and parameters: {'hidden_dim': 128, 'num_layers': 6}. Best is trial 22 with value: 0.8083674311637878.
[I 2026-02-22 13:39:43,255] Trial 28 finished with value: 0.8292554616928101 and parameters: {'hidden_dim': 256, 'num_layers': 4}. Best is trial 28 with value: 0.8292554616928101.
[I 2026-02-22 13:40:01,183] Trial 29 finished with value: 0.8377370238304138 and parameters: {'hidden_dim': 256, 'num_layers': 4}. Best is trial 29 with value: 0.8377370238304138.

In [66]:
# Contrastive stage:

# temperature = trial.suggest_float("temperature", 0.05, 0.5, log=True)
# exclusion_radius = trial.suggest_int("exclusion_radius", 2, 20)

class ContrastiveStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        temperature = trial.suggest_float("temperature", 0.05, 0.5, log=True)
        exclusion_radius = trial.suggest_int("exclusion_radius", 2, 20)

        contrastive_params = ContrastiveParams(temperature, exclusion_radius)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("contrastive_params", contrastive_params.__dict__)

        return score
    
study_contrastive = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="contrastive_stage",
    load_if_exists=True
)

study_contrastive.optimize(ContrastiveStageObjective(data, device, 
                                                     {
    **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"]
}
), n_trials=50)

[I 2026-02-22 14:36:38,179] Using an existing study with name 'contrastive_stage' instead of creating a new one.

[I 2026-02-22 14:36:55,646] Trial 2 finished with value: 0.7239099740982056 and parameters: {'temperature': 0.20124654648298504, 'exclusion_radius': 9}. Best is trial 2 with value: 0.7239099740982056.
[I 2026-02-22 14:37:13,097] Trial 3 finished with value: 0.7523349523544312 and parameters: {'temperature': 0.06868513558308588, 'exclusion_radius': 4}. Best is trial 3 with value: 0.7523349523544312.
[I 2026-02-22 14:37:30,429] Trial 4 finished with value: 0.5766209959983826 and parameters: {'temperature': 0.0535096474830974, 'exclusion_radius': 5}. Best is trial 3 with value: 0.7523349523544312.
[I 2026-02-22 14:37:47,662] Trial 5 finished with value: 0.8162449598312378 and parameters: {'temperature': 0.15466840894620842, 'exclusion_radius': 13}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:38:04,924] Trial 6 finished with value: 0.7584587335586548 and parameters: {'temperature': 0.17928329679413899, 'exclusion_radius': 16}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:38:22,182] Trial 7 finished with value: 0.6013724207878113 and parameters: {'temperature': 0.05988951763798633, 'exclusion_radius': 15}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:38:39,603] Trial 8 finished with value: 0.8111820816993713 and parameters: {'temperature': 0.08419592770978622, 'exclusion_radius': 7}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:38:57,035] Trial 9 finished with value: 0.8073904514312744 and parameters: {'temperature': 0.09620197618942833, 'exclusion_radius': 3}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:39:14,690] Trial 10 finished with value: 0.6663385629653931 and parameters: {'temperature': 0.28670732223053097, 'exclusion_radius': 8}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:39:32,613] Trial 11 finished with value: 0.778313159942627 and parameters: {'temperature': 0.08399977822796899, 'exclusion_radius': 20}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:39:50,679] Trial 12 finished with value: 0.6672726273536682 and parameters: {'temperature': 0.49970467892931403, 'exclusion_radius': 13}. Best is trial 5 with value: 0.8162449598312378.
[I 2026-02-22 14:40:08,982] Trial 13 finished with value: 0.8291784524917603 and parameters: {'temperature': 0.11958898327791435, 'exclusion_radius': 10}. Best is trial 13 with value: 0.8291784524917603.
[I 2026-02-22 14:40:27,054] Trial 14 finished with value: 0.834494948387146 and parameters: {'temperature': 0.1372508991291103, 'exclusion_radius': 11}. Best is trial 14 with value: 0.834494948387146.
[I 2026-02-22 14:40:45,049] Trial 15 finished with value: 0.8405554294586182 and parameters: {'temperature': 0.12527207728076964, 'exclusion_radius': 11}. Best is trial 15 with value: 0.8405554294586182.
[I 2026-02-22 14:41:02,929] Trial 16 finished with value: 0.7264900207519531 and parameters: {'temperature': 0.26803509894175026, 'exclusion_radius': 12}. Best is trial 15 with value: 0.8405554294586182.
[I 2026-02-22 14:41:20,709] Trial 17 finished with value: 0.8452296257019043 and parameters: {'temperature': 0.12140481854747597, 'exclusion_radius': 18}. Best is trial 17 with value: 0.8452296257019043.
[I 2026-02-22 14:41:38,401] Trial 18 finished with value: 0.8523362874984741 and parameters: {'temperature': 0.11063773809939827, 'exclusion_radius': 19}. Best is trial 18 with value: 0.8523362874984741.
[I 2026-02-22 14:41:56,178] Trial 19 finished with value: 0.8513732552528381 and parameters: {'temperature': 0.10391237502401705, 'exclusion_radius': 20}. Best is trial 18 with value: 0.8523362874984741.
[I 2026-02-22 14:42:13,934] Trial 20 finished with value: 0.8223588466644287 and parameters: {'temperature': 0.09778440783942646, 'exclusion_radius': 20}. Best is trial 18 with value: 0.8523362874984741.
[I 2026-02-22 14:42:31,561] Trial 21 finished with value: 0.7391448020935059 and parameters: {'temperature': 0.22352750500342794, 'exclusion_radius': 17}. Best is trial 18 with value: 0.8523362874984741.
[I 2026-02-22 14:42:49,137] Trial 22 finished with value: 0.6815778613090515 and parameters: {'temperature': 0.07105335124624189, 'exclusion_radius': 18}. Best is trial 18 with value: 0.8523362874984741.
[I 2026-02-22 14:43:06,711] Trial 23 finished with value: 0.8555546998977661 and parameters: {'temperature': 0.10901392823581604, 'exclusion_radius': 18}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:43:24,236] Trial 24 finished with value: 0.85517817735672 and parameters: {'temperature': 0.1040056671310527, 'exclusion_radius': 20}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:43:41,823] Trial 25 finished with value: 0.8119645714759827 and parameters: {'temperature': 0.1493987840937484, 'exclusion_radius': 18}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:43:59,344] Trial 26 finished with value: 0.7207905054092407 and parameters: {'temperature': 0.07748098247225026, 'exclusion_radius': 15}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:44:16,866] Trial 27 finished with value: 0.8531937599182129 and parameters: {'temperature': 0.11435441610030611, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:44:34,418] Trial 28 finished with value: 0.8166884779930115 and parameters: {'temperature': 0.09219862364813441, 'exclusion_radius': 16}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:44:51,929] Trial 29 finished with value: 0.7819236516952515 and parameters: {'temperature': 0.16892247103655894, 'exclusion_radius': 15}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:45:09,445] Trial 30 finished with value: 0.8261153697967529 and parameters: {'temperature': 0.14428861282307448, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:45:26,938] Trial 31 finished with value: 0.7505987286567688 and parameters: {'temperature': 0.20051255471022517, 'exclusion_radius': 17}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:45:44,750] Trial 32 finished with value: 0.5932554006576538 and parameters: {'temperature': 0.062031370170696175, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:46:02,287] Trial 33 finished with value: 0.8433424234390259 and parameters: {'temperature': 0.11883930266874074, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:46:19,803] Trial 34 finished with value: 0.8490177392959595 and parameters: {'temperature': 0.10766860869242721, 'exclusion_radius': 17}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:46:37,330] Trial 35 finished with value: 0.8540658950805664 and parameters: {'temperature': 0.10911276194717508, 'exclusion_radius': 20}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:46:54,871] Trial 36 finished with value: 0.8019671440124512 and parameters: {'temperature': 0.0883515776065563, 'exclusion_radius': 20}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:47:12,421] Trial 37 finished with value: 0.6982142329216003 and parameters: {'temperature': 0.07400316177226096, 'exclusion_radius': 14}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:47:29,973] Trial 38 finished with value: 0.8338791131973267 and parameters: {'temperature': 0.1320428281613658, 'exclusion_radius': 16}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:47:47,718] Trial 39 finished with value: 0.5876692533493042 and parameters: {'temperature': 0.056084889082294996, 'exclusion_radius': 6}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:48:05,295] Trial 40 finished with value: 0.78514564037323 and parameters: {'temperature': 0.18601535295529317, 'exclusion_radius': 18}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:48:22,864] Trial 41 finished with value: 0.7522100806236267 and parameters: {'temperature': 0.08099732852980311, 'exclusion_radius': 20}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:48:40,486] Trial 42 finished with value: 0.6036837697029114 and parameters: {'temperature': 0.06281090582166034, 'exclusion_radius': 17}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:48:58,072] Trial 43 finished with value: 0.8517827391624451 and parameters: {'temperature': 0.1126143878825604, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:49:15,661] Trial 44 finished with value: 0.847101092338562 and parameters: {'temperature': 0.10103118165427269, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:49:33,531] Trial 45 finished with value: 0.7002428770065308 and parameters: {'temperature': 0.16498319445972548, 'exclusion_radius': 2}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:49:51,120] Trial 46 finished with value: 0.846402645111084 and parameters: {'temperature': 0.10911267939031627, 'exclusion_radius': 18}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:50:08,711] Trial 47 finished with value: 0.8102515935897827 and parameters: {'temperature': 0.08966991975896536, 'exclusion_radius': 20}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:50:26,312] Trial 48 finished with value: 0.8303635120391846 and parameters: {'temperature': 0.13446669316660184, 'exclusion_radius': 14}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:50:44,084] Trial 49 finished with value: 0.7922784090042114 and parameters: {'temperature': 0.14869042252870776, 'exclusion_radius': 9}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:51:01,712] Trial 50 finished with value: 0.6252433061599731 and parameters: {'temperature': 0.4858786225817626, 'exclusion_radius': 19}. Best is trial 23 with value: 0.8555546998977661.
[I 2026-02-22 14:51:19,315] Trial 51 finished with value: 0.8286656737327576 and parameters: {'temperature': 0.09723736223183546, 'exclusion_radius': 16}. Best is trial 23 with value: 0.8555546998977661.

In [67]:
# Augmentation stage:

# mask_ratio = trial.suggest_float("mask_ratio", 0.1, 0.4)
# jitter_sigma = trial.suggest_float("jitter_sigma", 0.005, 0.05, log=True)

class AugmentationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        mask_ratio = trial.suggest_float("mask_ratio", 0.1, 0.4)
        jitter_sigma = trial.suggest_float("jitter_sigma", 0.005, 0.05, log=True)

        aug_params = AugmentationParams(mask_ratio, jitter_sigma)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("aug_params", aug_params.__dict__)

        return score
    
study_aug = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="augmentation_stage",
    load_if_exists=True
)
study_aug.optimize(AugmentationStageObjective(data, device, 
                                                     {
    **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"]
}
), n_trials=50)

[I 2026-02-22 14:55:14,501] A new study created in RDB with name: augmentation_stage
[I 2026-02-22 14:55:31,973] Trial 0 finished with value: 0.822404146194458 and parameters: {'mask_ratio': 0.3160850114434691, 'jitter_sigma': 0.0067355966719553914}. Best is trial 0 with value: 0.822404146194458.
[I 2026-02-22 14:55:49,260] Trial 1 finished with value: 0.8854341506958008 and parameters: {'mask_ratio': 0.12468497408563146, 'jitter_sigma': 0.005892071487060923}. Best is trial 1 with value: 0.8854341506958008.
[I 2026-02-22 14:56:06,589] Trial 2 finished with value: 0.7065039873123169 and parameters: {'mask_ratio': 0.3534629492038706, 'jitter_sigma': 0.010486868782593584}. Best is trial 1 with value: 0.8854341506958008.
[I 2026-02-22 14:56:23,992] Trial 3 finished with value: 0.8739010095596313 and parameters: {'mask_ratio': 0.1607389580190983, 'jitter_sigma': 0.040570314897763644}. Best is trial 1 with value: 0.8854341506958008.
[I 2026-02-22 14:56:41,518] Trial 4 finished with value: 0.852245569229126 and parameters: {'mask_ratio': 0.22633436314679076, 'jitter_sigma': 0.04258559828899639}. Best is trial 1 with value: 0.8854341506958008.
[I 2026-02-22 14:56:58,999] Trial 5 finished with value: 0.8511157631874084 and parameters: {'mask_ratio': 0.2162250820009235, 'jitter_sigma': 0.0332659395165249}. Best is trial 1 with value: 0.8854341506958008.
[I 2026-02-22 14:57:16,436] Trial 6 finished with value: 0.8944379091262817 and parameters: {'mask_ratio': 0.12357179561706015, 'jitter_sigma': 0.04079657170315576}. Best is trial 6 with value: 0.8944379091262817.
[I 2026-02-22 14:57:34,177] Trial 7 finished with value: 0.8425043821334839 and parameters: {'mask_ratio': 0.2386517547971346, 'jitter_sigma': 0.04040980395419019}. Best is trial 6 with value: 0.8944379091262817.
[I 2026-02-22 14:57:52,557] Trial 8 finished with value: 0.6849625110626221 and parameters: {'mask_ratio': 0.3654450723251605, 'jitter_sigma': 0.015886789276021215}. Best is trial 6 with value: 0.8944379091262817.
[I 2026-02-22 14:58:11,491] Trial 9 finished with value: 0.8363410234451294 and parameters: {'mask_ratio': 0.2167321000034807, 'jitter_sigma': 0.017904661947856445}. Best is trial 6 with value: 0.8944379091262817.
[I 2026-02-22 14:58:30,587] Trial 10 finished with value: 0.8955762982368469 and parameters: {'mask_ratio': 0.10773608832657922, 'jitter_sigma': 0.02514029713636866}. Best is trial 10 with value: 0.8955762982368469.
[I 2026-02-22 14:58:49,730] Trial 11 finished with value: 0.8961207270622253 and parameters: {'mask_ratio': 0.10237142233380916, 'jitter_sigma': 0.02473990444067}. Best is trial 11 with value: 0.8961207270622253.
[I 2026-02-22 14:59:09,094] Trial 12 finished with value: 0.8991715312004089 and parameters: {'mask_ratio': 0.10133107822327414, 'jitter_sigma': 0.023992256394836375}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 14:59:27,854] Trial 13 finished with value: 0.8713544011116028 and parameters: {'mask_ratio': 0.16225385743413728, 'jitter_sigma': 0.022755628200850853}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 14:59:47,625] Trial 14 finished with value: 0.8619242906570435 and parameters: {'mask_ratio': 0.16191267483953908, 'jitter_sigma': 0.026138218309624525}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:00:05,970] Trial 15 finished with value: 0.7752240300178528 and parameters: {'mask_ratio': 0.288129000382253, 'jitter_sigma': 0.010903550800539438}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:00:24,152] Trial 16 finished with value: 0.8927270770072937 and parameters: {'mask_ratio': 0.10095444667724122, 'jitter_sigma': 0.011696050018924367}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:00:42,239] Trial 17 finished with value: 0.8566166758537292 and parameters: {'mask_ratio': 0.18393216132858525, 'jitter_sigma': 0.019975809231579957}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:01:00,144] Trial 18 finished with value: 0.8274173736572266 and parameters: {'mask_ratio': 0.2923728795042727, 'jitter_sigma': 0.030676218916891644}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:01:18,234] Trial 19 finished with value: 0.6934909820556641 and parameters: {'mask_ratio': 0.3991740590600602, 'jitter_sigma': 0.013297554475976095}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:01:36,188] Trial 20 finished with value: 0.862596333026886 and parameters: {'mask_ratio': 0.1894196844401836, 'jitter_sigma': 0.030296160782225072}. Best is trial 12 with value: 0.8991715312004089.
[I 2026-02-22 15:01:54,064] Trial 21 finished with value: 0.8999641537666321 and parameters: {'mask_ratio': 0.10192306290847612, 'jitter_sigma': 0.021674647978106944}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:02:11,968] Trial 22 finished with value: 0.885558009147644 and parameters: {'mask_ratio': 0.13392740794579447, 'jitter_sigma': 0.020412787127895456}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:02:29,747] Trial 23 finished with value: 0.8801264762878418 and parameters: {'mask_ratio': 0.14185088194084133, 'jitter_sigma': 0.015099517600072051}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:02:47,439] Trial 24 finished with value: 0.8997435569763184 and parameters: {'mask_ratio': 0.10775739460896393, 'jitter_sigma': 0.026571027939300617}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:03:05,128] Trial 25 finished with value: 0.8503047823905945 and parameters: {'mask_ratio': 0.18596571122044256, 'jitter_sigma': 0.03202941307914945}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:03:22,953] Trial 26 finished with value: 0.8882778882980347 and parameters: {'mask_ratio': 0.13954824805395827, 'jitter_sigma': 0.04855573795777203}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:03:40,916] Trial 27 finished with value: 0.8830199837684631 and parameters: {'mask_ratio': 0.14956265762823676, 'jitter_sigma': 0.008034486277196141}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:03:58,971] Trial 28 finished with value: 0.806406557559967 and parameters: {'mask_ratio': 0.26393315772207426, 'jitter_sigma': 0.018256393219915106}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:04:16,961] Trial 29 finished with value: 0.892532467842102 and parameters: {'mask_ratio': 0.11874894260331034, 'jitter_sigma': 0.02786888250185825}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:04:34,850] Trial 30 finished with value: 0.8649466037750244 and parameters: {'mask_ratio': 0.17658832522377055, 'jitter_sigma': 0.02219089841796584}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:04:52,732] Trial 31 finished with value: 0.8998695015907288 and parameters: {'mask_ratio': 0.10580573058999888, 'jitter_sigma': 0.02513486877680702}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:05:10,603] Trial 32 finished with value: 0.8902567028999329 and parameters: {'mask_ratio': 0.11902086676075423, 'jitter_sigma': 0.034802681007162335}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:05:28,445] Trial 33 finished with value: 0.8926393985748291 and parameters: {'mask_ratio': 0.12152569903460174, 'jitter_sigma': 0.016750308102469767}. Best is trial 21 with value: 0.8999641537666321.
[I 2026-02-22 15:05:47,292] Trial 34 finished with value: 0.9001360535621643 and parameters: {'mask_ratio': 0.10030096038575573, 'jitter_sigma': 0.022226300134215674}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:06:05,992] Trial 35 finished with value: 0.872873842716217 and parameters: {'mask_ratio': 0.1470910431479725, 'jitter_sigma': 0.02062889675024755}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:06:25,203] Trial 36 finished with value: 0.8884106278419495 and parameters: {'mask_ratio': 0.13050801756399652, 'jitter_sigma': 0.005003584065111345}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:06:44,386] Trial 37 finished with value: 0.869894802570343 and parameters: {'mask_ratio': 0.1659299910704491, 'jitter_sigma': 0.014250942851090676}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:07:03,581] Trial 38 finished with value: 0.8507347106933594 and parameters: {'mask_ratio': 0.19838290272444106, 'jitter_sigma': 0.03631000944530627}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:07:22,776] Trial 39 finished with value: 0.8962171077728271 and parameters: {'mask_ratio': 0.1159908873981342, 'jitter_sigma': 0.02789190393597463}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:07:40,979] Trial 40 finished with value: 0.7159581780433655 and parameters: {'mask_ratio': 0.3399424195469981, 'jitter_sigma': 0.01815763112410362}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:07:58,960] Trial 41 finished with value: 0.9000110626220703 and parameters: {'mask_ratio': 0.10470519107673167, 'jitter_sigma': 0.023142779144531875}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:08:16,951] Trial 42 finished with value: 0.892813503742218 and parameters: {'mask_ratio': 0.1273561299668616, 'jitter_sigma': 0.022055856985573306}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:08:35,302] Trial 43 finished with value: 0.8970744609832764 and parameters: {'mask_ratio': 0.11196763462070147, 'jitter_sigma': 0.02783391389375257}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:08:53,245] Trial 44 finished with value: 0.8767214417457581 and parameters: {'mask_ratio': 0.14987703191576152, 'jitter_sigma': 0.037094741066112366}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:09:11,451] Trial 45 finished with value: 0.8997811675071716 and parameters: {'mask_ratio': 0.10128042480998954, 'jitter_sigma': 0.019508962138290134}. Best is trial 34 with value: 0.9001360535621643.
[I 2026-02-22 15:09:29,397] Trial 46 finished with value: 0.9013510346412659 and parameters: {'mask_ratio': 0.10112014206194599, 'jitter_sigma': 0.019884546877356246}. Best is trial 46 with value: 0.9013510346412659.
[I 2026-02-22 15:09:47,609] Trial 47 finished with value: 0.8886250853538513 and parameters: {'mask_ratio': 0.1299986905960176, 'jitter_sigma': 0.022886431248629678}. Best is trial 46 with value: 0.9013510346412659.
[I 2026-02-22 15:10:05,702] Trial 48 finished with value: 0.8463265299797058 and parameters: {'mask_ratio': 0.2060755635745976, 'jitter_sigma': 0.012957008746811223}. Best is trial 46 with value: 0.9013510346412659.
[I 2026-02-22 15:10:23,641] Trial 49 finished with value: 0.8743696212768555 and parameters: {'mask_ratio': 0.15421931765056948, 'jitter_sigma': 0.017488355205011397}. Best is trial 46 with value: 0.9013510346412659.

In [68]:
# Optimization stage:

# learning_rate = trial.suggest_float("learning_rate", 1e-4, 3e-3, log=True)
# batch_size = trial.suggest_categorical("batch_size", [32, 64, 128])

class OptimizationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        learning_rate = trial.suggest_float("learning_rate", 1e-4, 3e-3, log=True)
        batch_size = trial.suggest_categorical("batch_size", [32, 64, 128])

        opt_params = OptimizationParams(learning_rate, batch_size)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])
        aug_params = AugmentationParams(self.fixed_params["mask_ratio"], self.fixed_params["jitter_sigma"])

        train_loader = create_loader(self.data, window_size, batch_size)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("opt_params", opt_params.__dict__)

        return score
    
study_opt = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="optimization_stage",
    load_if_exists=True
)
study_opt.optimize(OptimizationStageObjective(data, device,
                                                     {
    **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"],
    **study_aug.best_trial.user_attrs["aug_params"]
}), n_trials=50)

[I 2026-02-22 15:20:45,762] A new study created in RDB with name: optimization_stage
[I 2026-02-22 15:20:55,699] Trial 0 finished with value: 0.8872004747390747 and parameters: {'learning_rate': 0.001964145474122741, 'batch_size': 32}. Best is trial 0 with value: 0.8872004747390747.
[I 2026-02-22 15:21:29,934] Trial 1 finished with value: 0.8732810020446777 and parameters: {'learning_rate': 0.0026197575781272244, 'batch_size': 128}. Best is trial 0 with value: 0.8872004747390747.
[I 2026-02-22 15:21:47,272] Trial 2 finished with value: 0.89781653881073 and parameters: {'learning_rate': 0.0009812743476000573, 'batch_size': 64}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:22:21,415] Trial 3 finished with value: 0.8366058468818665 and parameters: {'learning_rate': 0.0002696060521162218, 'batch_size': 128}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:22:55,188] Trial 4 finished with value: 0.8967544436454773 and parameters: {'learning_rate': 0.0016146214144805012, 'batch_size': 128}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:23:05,307] Trial 5 finished with value: 0.8558799028396606 and parameters: {'learning_rate': 0.0001307557418789929, 'batch_size': 32}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:23:23,475] Trial 6 finished with value: 0.8903821706771851 and parameters: {'learning_rate': 0.0028393570090008736, 'batch_size': 64}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:24:00,093] Trial 7 finished with value: 0.7814159393310547 and parameters: {'learning_rate': 0.00011467282292937005, 'batch_size': 128}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:24:19,239] Trial 8 finished with value: 0.8902493715286255 and parameters: {'learning_rate': 0.0006958394183856802, 'batch_size': 64}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:24:56,562] Trial 9 finished with value: 0.8739669919013977 and parameters: {'learning_rate': 0.0007471627120140729, 'batch_size': 128}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:25:15,515] Trial 10 finished with value: 0.8720104098320007 and parameters: {'learning_rate': 0.0003532863289082431, 'batch_size': 64}. Best is trial 2 with value: 0.89781653881073.
[I 2026-02-22 15:25:34,448] Trial 11 finished with value: 0.8987584114074707 and parameters: {'learning_rate': 0.0013926352324370504, 'batch_size': 64}. Best is trial 11 with value: 0.8987584114074707.
[I 2026-02-22 15:25:53,131] Trial 12 finished with value: 0.8934859037399292 and parameters: {'learning_rate': 0.0010280220174359949, 'batch_size': 64}. Best is trial 11 with value: 0.8987584114074707.
[I 2026-02-22 15:26:11,588] Trial 13 finished with value: 0.9002804160118103 and parameters: {'learning_rate': 0.0011621673937864234, 'batch_size': 64}. Best is trial 13 with value: 0.9002804160118103.
[I 2026-02-22 15:26:30,240] Trial 14 finished with value: 0.9022127985954285 and parameters: {'learning_rate': 0.0014528542853459914, 'batch_size': 64}. Best is trial 14 with value: 0.9022127985954285.
[I 2026-02-22 15:26:48,520] Trial 15 finished with value: 0.8814544677734375 and parameters: {'learning_rate': 0.00042554012750377487, 'batch_size': 64}. Best is trial 14 with value: 0.9022127985954285.
[I 2026-02-22 15:26:58,742] Trial 16 finished with value: 0.9031230211257935 and parameters: {'learning_rate': 0.001216193897587712, 'batch_size': 32}. Best is trial 16 with value: 0.9031230211257935.
[I 2026-02-22 15:27:09,047] Trial 17 finished with value: 0.8935293555259705 and parameters: {'learning_rate': 0.0019778623876947005, 'batch_size': 32}. Best is trial 16 with value: 0.9031230211257935.
[I 2026-02-22 15:27:19,310] Trial 18 finished with value: 0.893038809299469 and parameters: {'learning_rate': 0.0006101666974661191, 'batch_size': 32}. Best is trial 16 with value: 0.9031230211257935.
[I 2026-02-22 15:27:29,547] Trial 19 finished with value: 0.8641965985298157 and parameters: {'learning_rate': 0.0002068915115414819, 'batch_size': 32}. Best is trial 16 with value: 0.9031230211257935.
[I 2026-02-22 15:27:39,726] Trial 20 finished with value: 0.8944918513298035 and parameters: {'learning_rate': 0.0008650034794465357, 'batch_size': 32}. Best is trial 16 with value: 0.9031230211257935.
[I 2026-02-22 15:27:57,926] Trial 21 finished with value: 0.9049080014228821 and parameters: {'learning_rate': 0.0013282672252693248, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:28:16,391] Trial 22 finished with value: 0.9029194116592407 and parameters: {'learning_rate': 0.0013761521149481856, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:28:34,621] Trial 23 finished with value: 0.8858010172843933 and parameters: {'learning_rate': 0.0005278942270691594, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:28:44,871] Trial 24 finished with value: 0.8849917650222778 and parameters: {'learning_rate': 0.0019976910159770597, 'batch_size': 32}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:29:03,149] Trial 25 finished with value: 0.8988392353057861 and parameters: {'learning_rate': 0.0011733926767901696, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:29:13,599] Trial 26 finished with value: 0.8984267711639404 and parameters: {'learning_rate': 0.001591236160426022, 'batch_size': 32}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:29:31,858] Trial 27 finished with value: 0.8935513496398926 and parameters: {'learning_rate': 0.0023182401169843047, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:29:50,104] Trial 28 finished with value: 0.8937968611717224 and parameters: {'learning_rate': 0.0008608231204702451, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:30:00,524] Trial 29 finished with value: 0.9010351896286011 and parameters: {'learning_rate': 0.001305356086005822, 'batch_size': 32}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:30:10,699] Trial 30 finished with value: 0.8872806429862976 and parameters: {'learning_rate': 0.00047042604774676154, 'batch_size': 32}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:30:29,228] Trial 31 finished with value: 0.897181510925293 and parameters: {'learning_rate': 0.0018135340155628209, 'batch_size': 64}. Best is trial 21 with value: 0.9049080014228821.
[I 2026-02-22 15:30:48,546] Trial 32 finished with value: 0.9067237377166748 and parameters: {'learning_rate': 0.0014605942073434486, 'batch_size': 64}. Best is trial 32 with value: 0.9067237377166748.
[I 2026-02-22 15:31:07,250] Trial 33 finished with value: 0.8889755010604858 and parameters: {'learning_rate': 0.0022810716675990433, 'batch_size': 64}. Best is trial 32 with value: 0.9067237377166748.
[I 2026-02-22 15:31:25,588] Trial 34 finished with value: 0.8971344828605652 and parameters: {'learning_rate': 0.0010368572498158787, 'batch_size': 64}. Best is trial 32 with value: 0.9067237377166748.
[I 2026-02-22 15:32:01,512] Trial 35 finished with value: 0.8804289698600769 and parameters: {'learning_rate': 0.0008996406807282037, 'batch_size': 128}. Best is trial 32 with value: 0.9067237377166748.
[I 2026-02-22 15:32:19,528] Trial 36 finished with value: 0.898369550704956 and parameters: {'learning_rate': 0.0016631269204819296, 'batch_size': 64}. Best is trial 32 with value: 0.9067237377166748.
[I 2026-02-22 15:32:37,612] Trial 37 finished with value: 0.910244882106781 and parameters: {'learning_rate': 0.0012543308801674451, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:33:13,146] Trial 38 finished with value: 0.8759922385215759 and parameters: {'learning_rate': 0.002922087407124012, 'batch_size': 128}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:33:31,856] Trial 39 finished with value: 0.8885707259178162 and parameters: {'learning_rate': 0.000643960173135792, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:33:42,235] Trial 40 finished with value: 0.8834133744239807 and parameters: {'learning_rate': 0.002152595755286884, 'batch_size': 32}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:34:00,405] Trial 41 finished with value: 0.9012959003448486 and parameters: {'learning_rate': 0.0012789046942833443, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:34:18,547] Trial 42 finished with value: 0.8941965103149414 and parameters: {'learning_rate': 0.0007622615328864531, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:34:36,985] Trial 43 finished with value: 0.8971752524375916 and parameters: {'learning_rate': 0.0015583554801376245, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:34:55,124] Trial 44 finished with value: 0.9017075300216675 and parameters: {'learning_rate': 0.0010957930268725576, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:35:30,909] Trial 45 finished with value: 0.8997808694839478 and parameters: {'learning_rate': 0.001799158472931677, 'batch_size': 128}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:35:49,397] Trial 46 finished with value: 0.8978145718574524 and parameters: {'learning_rate': 0.001395835208678212, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:36:07,839] Trial 47 finished with value: 0.9019293189048767 and parameters: {'learning_rate': 0.0012445667502619534, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:36:25,951] Trial 48 finished with value: 0.8991289138793945 and parameters: {'learning_rate': 0.0009470762451437169, 'batch_size': 64}. Best is trial 37 with value: 0.910244882106781.
[I 2026-02-22 15:37:02,151] Trial 49 finished with value: 0.8706086874008179 and parameters: {'learning_rate': 0.002549013378843314, 'batch_size': 128}. Best is trial 37 with value: 0.910244882106781.

In [ ]:
class TS2VecHyperparameterPipeline:

    def __init__(self, data, device):
        self.data = data
        self.device = device
        self.best_params = {}

    def run_stage(self, objective_class, n_trials=30):
        study = optuna.create_study(
            direction="maximize",
            sampler=optuna.samplers.TPESampler()
        )

        study.optimize(
            objective_class(self.data, self.device, self.best_params),
            n_trials=n_trials
        )

        self.best_params.update(study.best_params)

        return study

    def run_full_pipeline(self):
        study_window = self.run_stage(WindowStageObjective)
        study_arch = self.run_stage(ArchitectureStageObjective)
        # Add remaining stages here
        study_contrastive = self.run_stage(ContrastiveStageObjective)
        study_aug = self.run_stage(AugmentationStageObjective)
        study_opt = self.run_stage(OptimizationStageObjective)
        return {
            "window": study_window,
            "architecture": study_arch,
            "contrastive": study_contrastive,
            "augmentation": study_aug,
            "optimization": study_opt
        }

In [69]:
# list all the best parameters from each stage
param_summary = {
    "window": study_window.best_trial.user_attrs["window_params"],
    "architecture": study_arch.best_trial.user_attrs["arch_params"],
    "contrastive": study_contrastive.best_trial.user_attrs["contrastive_params"],
    "augmentation": study_aug.best_trial.user_attrs["aug_params"],
    "optimization": study_opt.best_trial.user_attrs["opt_params"]
}

In [70]:
param_summary

{'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 4},
 'contrastive': {'temperature': 0.10901392823581604, 'exclusion_radius': 18},
 'augmentation': {'mask_ratio': 0.10112014206194599,
  'jitter_sigma': 0.019884546877356246},
 'optimization': {'learning_rate': 0.0012543308801674451, 'batch_size': 64}}