In [1]:
from torch.utils.data import Dataset, DataLoader
import torch
import pandas as pd
import numpy as np
import pickle

In [2]:
device ="mps"

In [38]:
with open('../../data/complete_features.pkl', 'rb') as f:
    all_data = pickle.load(f)

In [39]:
data = all_data["scaled_featured"].copy()
data["close"] = all_data["Close"]

In [40]:
# log returns
data["log_return"] = np.log(data["close"] / data["close"].shift(1))
data.dropna(inplace=True)

In [41]:
data

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20,close,log_return
Date,,,,,,,,,,,,,,
2008-07-08,-1.211754,-1.882225,2.077736,-0.022097,-1.117078,-1.046961,-0.542321,-2.455523,1.450259,0.981827,-2.206775,-0.513460,3988.550049,-0.010339
2008-07-09,-0.957426,-1.882225,2.289506,1.636228,-1.218247,-0.338846,-0.561373,-1.988903,1.476862,0.785786,-1.960992,-0.565134,4157.100098,0.041390
2008-07-10,-0.975703,-1.882225,2.287995,-0.006124,-1.013921,-0.474801,-0.596656,-2.401313,1.493754,0.505013,-1.940271,-0.562557,4162.200195,0.001226
2008-07-11,-1.136144,-1.882225,2.391761,0.804554,-1.050675,-0.396400,-0.475448,-2.987661,1.507027,0.400347,-2.078101,-0.510752,4049.000000,-0.027574
2008-07-14,-1.257924,-1.882225,2.371776,-0.148393,-1.268721,-0.518601,-0.436624,-3.173512,1.521334,0.430252,-2.071028,-0.455743,4039.699951,-0.002300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-15,0.375855,0.654743,-0.795604,0.021503,0.541634,-0.126723,-0.727148,-1.189892,-0.988672,-0.309058,0.314003,0.507783,25069.199219,-0.001785
2025-09-16,0.280399,0.654743,-0.833663,-0.287568,0.045456,-0.238463,-0.708679,-1.276291,-1.000565,-0.327333,0.453848,0.513354,25239.099609,0.006754
2025-09-17,0.260114,0.654743,-0.836851,-0.019044,0.154682,-0.363408,-0.703390,-1.335486,-1.009414,-0.239281,0.522324,0.511624,25330.250000,0.003605
2025-09-18,0.293060,0.654743,-0.832619,0.038097,0.230366,-0.508229,-0.737254,-1.044970,-1.020331,-0.299090,0.591810,0.309460,25423.599609,0.003679
2025-09-19,0.080198,0.654743,-0.823297,0.077298,0.164701,-0.717435,-0.742174,-1.146226,-1.028834,-0.229313,0.500421,0.283359,25327.050781,-0.003805

In [42]:
close = data["close"]
log_return = data["log_return"]

In [43]:
data.shape

(4218, 14)

In [44]:
data.drop(columns=["close","log_return"], inplace=True)

In [45]:
data

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20
Date,,,,,,,,,,,,
2008-07-08,-1.211754,-1.882225,2.077736,-0.022097,-1.117078,-1.046961,-0.542321,-2.455523,1.450259,0.981827,-2.206775,-0.513460
2008-07-09,-0.957426,-1.882225,2.289506,1.636228,-1.218247,-0.338846,-0.561373,-1.988903,1.476862,0.785786,-1.960992,-0.565134
2008-07-10,-0.975703,-1.882225,2.287995,-0.006124,-1.013921,-0.474801,-0.596656,-2.401313,1.493754,0.505013,-1.940271,-0.562557
2008-07-11,-1.136144,-1.882225,2.391761,0.804554,-1.050675,-0.396400,-0.475448,-2.987661,1.507027,0.400347,-2.078101,-0.510752
2008-07-14,-1.257924,-1.882225,2.371776,-0.148393,-1.268721,-0.518601,-0.436624,-3.173512,1.521334,0.430252,-2.071028,-0.455743
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-15,0.375855,0.654743,-0.795604,0.021503,0.541634,-0.126723,-0.727148,-1.189892,-0.988672,-0.309058,0.314003,0.507783
2025-09-16,0.280399,0.654743,-0.833663,-0.287568,0.045456,-0.238463,-0.708679,-1.276291,-1.000565,-0.327333,0.453848,0.513354
2025-09-17,0.260114,0.654743,-0.836851,-0.019044,0.154682,-0.363408,-0.703390,-1.335486,-1.009414,-0.239281,0.522324,0.511624
2025-09-18,0.293060,0.654743,-0.832619,0.038097,0.230366,-0.508229,-0.737254,-1.044970,-1.020331,-0.299090,0.591810,0.309460
2025-09-19,0.080198,0.654743,-0.823297,0.077298,0.164701,-0.717435,-0.742174,-1.146226,-1.028834,-0.229313,0.500421,0.283359

In [32]:
class TimeSeriesWindowDataset(Dataset):
    def __init__(self, data, window_size=60):
        """
        data: numpy array [T, D]
        """
        self.data = torch.tensor(data, dtype=torch.float32)
        self.window_size = window_size

    def __len__(self):
        return len(self.data) - self.window_size + 1

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.window_size]
        return x

window_size = 60
val_size = 0

train_size = int(len(data) * (1 - val_size))
train_data = data.iloc[:train_size]
val_data = data.iloc[train_size:]

train_dataset = TimeSeriesWindowDataset(train_data.values, window_size)
val_dataset = TimeSeriesWindowDataset(val_data.values, window_size)
combined_dataset = TimeSeriesWindowDataset(data.values, window_size)

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
combined_loader = DataLoader(combined_dataset, batch_size=batch_size, shuffle=False)

In [33]:
import torch.nn as nn
import torch.nn.functional as F

class TS2VecModel(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, num_layers=5):
        super(TS2VecModel, self).__init__()
        layers = []
        for i in range(num_layers):
            dilation = 2 ** i
            layers.append(nn.Conv1d(input_dim if i == 0 else hidden_dim, hidden_dim, kernel_size=3, padding=dilation, dilation=dilation))
            layers.append(nn.ReLU())
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        # x: [B, T, D]
        x = x.permute(0, 2, 1)  # [B, D, T]
        x = self.network(x)     # [B, H, T]
        x = x.permute(0, 2, 1)  # [B, T, H]
        # normalize
        x = F.normalize(x, p=2, dim=-1)
        return x
    
model = TS2VecModel(input_dim=data.shape[1], hidden_dim=128, num_layers=6).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [34]:
def time_mask(x, mask_ratio=0.2):
    B, T, D = x.shape
    mask_len = int(T * mask_ratio)
    start = np.random.randint(0, T - mask_len)
    x = x.clone()
    x[:, start:start+mask_len, :] = 0
    return x


def jitter(x, sigma=0.02):
    return x + sigma * torch.randn_like(x)


def temporal_pooling(z):
    if z.size(1) % 2 == 1:
        z = z[:, :-1]
    return z.reshape(z.size(0), z.size(1)//2, 2, z.size(2)).mean(dim=2)


def ts2vec_contrastive_loss_vectorized(
    z1, z2,
    temperature=0.1,
    base_exclusion_radius=5
):
    """
    z1, z2: [B, T, C]
    """
    B, T, C = z1.shape
    device = z1.device

    # flatten (instance, time)
    z1_flat = z1.reshape(B*T, C)
    z2_flat = z2.reshape(B*T, C)

    # cosine similarity == dot product because embeddings are normalized
    sim = torch.matmul(z1_flat, z2_flat.T) / temperature   # [BT, BT]

    # ----- temporal negative mask -----
    exclusion_radius = min(base_exclusion_radius, (T - 1) // 2)

    if exclusion_radius == 0:
        return torch.tensor(0.0, device=device)

    # time index per row
    time_idx = torch.arange(T, device=device).repeat(B)     # [BT]

    # batch index per row
    batch_idx = torch.arange(B, device=device).repeat_interleave(T)

    # same batch & temporally close → mask out
    temporal_dist = torch.abs(time_idx[:, None] - time_idx[None, :])
    same_batch = batch_idx[:, None] == batch_idx[None, :]

    invalid_negatives = same_batch & (temporal_dist <= exclusion_radius)

    # allow diagonal (positive pairs)
    diag = torch.eye(B*T, device=device, dtype=torch.bool)
    invalid_negatives = invalid_negatives & (~diag)

    # mask invalid negatives
    sim = sim.masked_fill(invalid_negatives, -1e9)

    # positives are diagonal
    labels = torch.arange(B*T, device=device)

    return F.cross_entropy(sim, labels)



def hierarchical_ts2vec_loss_v2(
    z1, z2,
    temperature=0.1,
    exclusion_radius=5,
    min_time=2
):
    total_loss = 0.0
    depth = 0

    while z1.size(1) >= min_time:
        T = z1.size(1)

        if T > 2 * exclusion_radius + 1:
            total_loss += ts2vec_contrastive_loss_vectorized(
                z1, z2,
                temperature,
                exclusion_radius
            )
            depth += 1

        z1 = temporal_pooling(z1)
        z2 = temporal_pooling(z2)

    return total_loss / max(depth, 1)

In [35]:
def temporal_contrast_score(Z, k=20):
    """
    This function computes the temporal contrast score for a given set of embeddings Z.
    Z: [T, C] numpy array of embeddings
    k: temporal gap for negative pairs
    """
    pos = []
    neg = []
    
    for i in range(len(Z) - k - 1):
        pos.append(np.dot(Z[i], Z[i+1]))
        neg.append(np.dot(Z[i], Z[i+k]))
    
    return np.mean(pos) - np.mean(neg)

# score = temporal_contrast_score(embeddings_full)
def temporal_contrast_score_multi(Z, pos_gap=1, neg_gaps=(10,20,40)):
    pos = []
    neg = []

    for i in range(len(Z) - max(neg_gaps) - 1):
        pos.append(np.dot(Z[i], Z[i+pos_gap]))
        for k in neg_gaps:
            neg.append(np.dot(Z[i], Z[i+k]))

    return np.mean(pos) - np.mean(neg)


from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

def predictive_score(Z, forward_returns):
    X = Z[:-1]
    y = forward_returns[1:]

    model = Ridge(alpha=1.0)
    model.fit(X, y)
    y_pred = model.predict(X)

    return r2_score(y, y_pred)

In [36]:
from dataclasses import dataclass

@dataclass
class WindowParams:
    window_size: int

@dataclass
class ArchitectureParams:
    hidden_dim: int
    num_layers: int

@dataclass
class ContrastiveParams:
    temperature: float
    exclusion_radius: int

@dataclass
class AugmentationParams:
    mask_ratio: float
    jitter_sigma: float

@dataclass
class OptimizationParams:
    learning_rate: float
    batch_size: int

In [37]:

long={'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 4},
 'contrastive': {'temperature': 0.10901392823581604, 'exclusion_radius': 18},
 'augmentation': {'mask_ratio': 0.10112014206194599,
  'jitter_sigma': 0.019884546877356246},
 'optimization': {'learning_rate': 0.0012543308801674451, 'batch_size': 64}}


short = {'window': 60,
 'architecture': {'hidden_dim': 128, 'num_layers': 4},
 'contrastive': {'temperature': 0.09418251159949012, 'exclusion_radius': 3},
 'augmentation': {'mask_ratio': 0.1153883102823196,
  'jitter_sigma': 0.006324426296094188},
 'optimization': {'learning_rate': 0.0017009936483370917, 'batch_size': 32}}



long_term_model_hyperparams_config = {
    "window_size": [30, 180, 30],  # range for window size  
    "hidden_dim": [ 128, 256,512],    
    "num_layers": [3, 10],
    "temperature": [0.05, 0.5],
    "exclusion_radius": [2, 20],
    "mask_ratio": [0.1, 0.5],
    "jitter_sigma": [0.005, 0.05],
    "learning_rate": [1e-4, 3e-3],
    "batch_size": [32,64,128]
}

short_term_model_hyperparams_config = {
    "window_size": [40, 80, 20],  # range for window size
    "hidden_dim": [32, 64, 128],
    "num_layers": [2, 7],
    "temperature": [0.05, 0.5],
    "exclusion_radius": [1, 5],
    "mask_ratio": [0.1, 0.5],
    "jitter_sigma": [0.005, 0.05],
    "learning_rate": [1e-4, 3e-3],
    "batch_size": [16,32,64]
}

mode = "short_term"  # or "short_term"

if mode == "long_term":
    hyperparams_config = long_term_model_hyperparams_config
else:
    hyperparams_config = short_term_model_hyperparams_config

In [46]:
import optuna
import torch
import numpy as np

class BaseTS2VecObjective:
    def __init__(self, data, device, fixed_params):
        self.data = data
        self.device = device
        self.fixed_params = fixed_params  # dict of params from previous stages

    def build_model(self, arch_params):
        return TS2VecModel(
            input_dim=self.data.shape[1],
            hidden_dim=arch_params.hidden_dim,
            num_layers=arch_params.num_layers
        ).to(self.device)

    def compute_score(self, model):
        model.eval()
        with torch.no_grad():
            full_tensor = torch.tensor(self.data.values, dtype=torch.float32).unsqueeze(0).to(self.device)
            z = model(full_tensor).squeeze(0).cpu().numpy()
            # use forward returns for predictive score
            return predictive_score(z, log_return.values)

    def train_model(self, model, train_loader, contrastive_params, aug_params, opt_params, epochs=3):
        optimizer = torch.optim.Adam(model.parameters(), lr=opt_params.learning_rate)

        model.train()
        for _ in range(epochs):  # small epochs for HPO
            for x in train_loader:
                x = x.to(self.device)
                x1 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)
                x2 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)

                z1 = model(x1)
                z2 = model(x2)

                loss = hierarchical_ts2vec_loss_v2(
                    z1, z2,
                    temperature=contrastive_params.temperature,
                    exclusion_radius=contrastive_params.exclusion_radius
                )

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
        return model

In [47]:
def create_loader(data, window_size, batch_size):
    dataset = TimeSeriesWindowDataset(data.values, window_size)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [48]:

class WindowStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):
        window_size = trial.suggest_int("window_size", hyperparams_config["window_size"][0] , hyperparams_config["window_size"][1], step=hyperparams_config["window_size"][2])

        window_params = WindowParams(window_size)

        train_loader = create_loader(self.data, window_size, batch_size=64)

        # fixed architecture for stage 0
        arch_params = ArchitectureParams(hidden_dim=128, num_layers=5)
        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("window_params", window_params.__dict__)

        return score

In [49]:
type(data.values)

numpy.ndarray

In [50]:
study_window = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="window_stage",
    load_if_exists=True
)

# suggest optimal trail count based on combination of parameters 


study_window.optimize(WindowStageObjective(data, device, {}), n_trials=7)

[I 2026-02-27 02:59:12,359] A new study created in RDB with name: window_stage
[I 2026-02-27 02:59:15,110] Trial 0 finished with value: 0.047421710637158054 and parameters: {'window_size': 60}. Best is trial 0 with value: 0.047421710637158054.
[I 2026-02-27 02:59:16,841] Trial 1 finished with value: 0.046483482350964 and parameters: {'window_size': 40}. Best is trial 0 with value: 0.047421710637158054.
[I 2026-02-27 02:59:18,895] Trial 2 finished with value: 0.05042184240229475 and parameters: {'window_size': 60}. Best is trial 2 with value: 0.05042184240229475.
[I 2026-02-27 02:59:20,946] Trial 3 finished with value: 0.050324870227630214 and parameters: {'window_size': 60}. Best is trial 2 with value: 0.05042184240229475.
[I 2026-02-27 02:59:22,361] Trial 4 finished with value: 0.053487711051270814 and parameters: {'window_size': 40}. Best is trial 4 with value: 0.053487711051270814.
[I 2026-02-27 02:59:24,417] Trial 5 finished with value: 0.04495540433129652 and parameters: {'window_size': 60}. Best is trial 4 with value: 0.053487711051270814.
[I 2026-02-27 02:59:28,129] Trial 6 finished with value: 0.05125499717421356 and parameters: {'window_size': 80}. Best is trial 4 with value: 0.053487711051270814.

In [ ]:
class ArchitectureStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        hidden_dim = trial.suggest_categorical("hidden_dim", hyperparams_config["hidden_dim"])
        num_layers = trial.suggest_int("num_layers", hyperparams_config["num_layers"][0], hyperparams_config["num_layers"][1])

        arch_params = ArchitectureParams(hidden_dim, num_layers)

        window_size = self.fixed_params["window_size"]

        train_loader = create_loader(self.data, window_size, batch_size=64)

        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("arch_params", arch_params.__dict__)

        return score
    
study_arch = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="arch_stage",
    load_if_exists=True
)

n_trials = 30

study_arch.optimize(ArchitectureStageObjective(data, device, {**study_window.best_trial.user_attrs["window_params"]} ), n_trials= 30)

[I 2026-02-27 03:02:15,977] Using an existing study with name 'arch_stage' instead of creating a new one.

[W 2026-02-27 03:02:15,999] Trial 32 failed with parameters: {} because of the following error: ValueError('CategoricalDistribution does not support dynamic value space.').
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/var/folders/jf/1r7jb1_s6ys1p0n0n56s2qsh0000gn/T/ipykernel_13531/82425197.py", line 5, in __call__
    hidden_dim = trial.suggest_categorical("hidden_dim", [32, 64, 128, 256, 512])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/trial/_trial.py", line 402, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/storages/_rdb/storage.py", line 579, in set_trial_param
    self._set_trial_param_without_commit(
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/storages/_rdb/storage.py", line 601, in _set_trial_param_without_commit
    trial_param.check_and_add(session, trial.study_id)
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/storages/_rdb/models.py", line 353, in check_and_add
    self._check_compatibility_with_previous_trial_param_distributions(session, study_id)
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/storages/_rdb/models.py", line 367, in _check_compatibility_with_previous_trial_param_distributions
    distributions.check_distribution_compatibility(
  File "/opt/miniconda3/lib/python3.12/site-packages/optuna/distributions.py", line 669, in check_distribution_compatibility
    raise ValueError(
ValueError: CategoricalDistribution does not support dynamic value space.
[W 2026-02-27 03:02:16,000] Trial 32 failed with value None.

ValueError: CategoricalDistribution does not support dynamic value space.

In [ ]:
# Contrastive stage:

# temperature = trial.suggest_float("temperature", 0.05, 0.5, log=True)
# exclusion_radius = trial.suggest_int("exclusion_radius", 2, 20)

class ContrastiveStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        temperature = trial.suggest_float("temperature", hyperparams_config["temperature"][0], hyperparams_config["temperature"][1], log=True)
        exclusion_radius = trial.suggest_int("exclusion_radius", hyperparams_config["exclusion_radius"][0], hyperparams_config["exclusion_radius"][1])

        contrastive_params = ContrastiveParams(temperature, exclusion_radius)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("contrastive_params", contrastive_params.__dict__)

        return score
    
study_contrastive = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="contrastive_stage",
    load_if_exists=True
)

study_contrastive.optimize(ContrastiveStageObjective(data, device, 
                                                     {
    **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"]
}
), n_trials=50)

[I 2026-02-23 12:58:56,162] Using an existing study with name 'contrastive_stage' instead of creating a new one.
[I 2026-02-23 12:58:58,077] Trial 0 finished with value: 0.6793023943901062 and parameters: {'temperature': 0.42552969467311136, 'exclusion_radius': 14}. Best is trial 0 with value: 0.6793023943901062.
[I 2026-02-23 12:58:59,947] Trial 1 finished with value: 0.7771525382995605 and parameters: {'temperature': 0.08357242993131461, 'exclusion_radius': 12}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:01,567] Trial 2 finished with value: 0.7561784386634827 and parameters: {'temperature': 0.131630796345488, 'exclusion_radius': 18}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:03,187] Trial 3 finished with value: 0.7088033556938171 and parameters: {'temperature': 0.3456678373263851, 'exclusion_radius': 18}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:04,811] Trial 4 finished with value: 0.6718445420265198 and parameters: {'temperature': 0.07287991129582129, 'exclusion_radius': 16}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:06,422] Trial 5 finished with value: 0.7202188968658447 and parameters: {'temperature': 0.23969370959923078, 'exclusion_radius': 16}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:08,370] Trial 6 finished with value: 0.7272889614105225 and parameters: {'temperature': 0.2589993013151443, 'exclusion_radius': 4}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:10,244] Trial 7 finished with value: 0.7613503932952881 and parameters: {'temperature': 0.07776721551955126, 'exclusion_radius': 12}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:11,865] Trial 8 finished with value: 0.741627037525177 and parameters: {'temperature': 0.16011052506024703, 'exclusion_radius': 20}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:13,494] Trial 9 finished with value: 0.7338858246803284 and parameters: {'temperature': 0.20368003757068334, 'exclusion_radius': 17}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:15,378] Trial 10 finished with value: 0.683006227016449 and parameters: {'temperature': 0.056023605567535696, 'exclusion_radius': 7}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:17,261] Trial 11 finished with value: 0.7720041871070862 and parameters: {'temperature': 0.09418064290898698, 'exclusion_radius': 11}. Best is trial 1 with value: 0.7771525382995605.
[I 2026-02-23 12:59:19,144] Trial 12 finished with value: 0.7929956912994385 and parameters: {'temperature': 0.10450051220982834, 'exclusion_radius': 9}. Best is trial 12 with value: 0.7929956912994385.
[I 2026-02-23 12:59:21,027] Trial 13 finished with value: 0.7865464091300964 and parameters: {'temperature': 0.10384421658110399, 'exclusion_radius': 8}. Best is trial 12 with value: 0.7929956912994385.
[I 2026-02-23 12:59:22,912] Trial 14 finished with value: 0.7851028442382812 and parameters: {'temperature': 0.14136696922375802, 'exclusion_radius': 8}. Best is trial 12 with value: 0.7929956912994385.
[I 2026-02-23 12:59:24,875] Trial 15 finished with value: 0.8059487342834473 and parameters: {'temperature': 0.11263856280799653, 'exclusion_radius': 3}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:26,975] Trial 16 finished with value: 0.7129924893379211 and parameters: {'temperature': 0.050149635123100805, 'exclusion_radius': 2}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:28,944] Trial 17 finished with value: 0.781484067440033 and parameters: {'temperature': 0.12206680560115755, 'exclusion_radius': 5}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:30,950] Trial 18 finished with value: 0.7362833619117737 and parameters: {'temperature': 0.16349666958594208, 'exclusion_radius': 2}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:32,914] Trial 19 finished with value: 0.765859842300415 and parameters: {'temperature': 0.06601541337019053, 'exclusion_radius': 5}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:34,802] Trial 20 finished with value: 0.7714518904685974 and parameters: {'temperature': 0.11709890619995984, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:36,687] Trial 21 finished with value: 0.7932488918304443 and parameters: {'temperature': 0.100470144257099, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:38,578] Trial 22 finished with value: 0.7844595909118652 and parameters: {'temperature': 0.09464316659534838, 'exclusion_radius': 10}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:40,544] Trial 23 finished with value: 0.7625433802604675 and parameters: {'temperature': 0.17898761084627351, 'exclusion_radius': 6}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:42,432] Trial 24 finished with value: 0.7690576910972595 and parameters: {'temperature': 0.10636767083667227, 'exclusion_radius': 14}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:44,397] Trial 25 finished with value: 0.7730038166046143 and parameters: {'temperature': 0.06600353056127498, 'exclusion_radius': 4}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:46,288] Trial 26 finished with value: 0.7823686599731445 and parameters: {'temperature': 0.08687489159414527, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:48,181] Trial 27 finished with value: 0.7701621055603027 and parameters: {'temperature': 0.1126918579543769, 'exclusion_radius': 13}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:50,073] Trial 28 finished with value: 0.7723492980003357 and parameters: {'temperature': 0.13726322995905832, 'exclusion_radius': 7}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:51,963] Trial 29 finished with value: 0.6600644588470459 and parameters: {'temperature': 0.38755126456428796, 'exclusion_radius': 10}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:53,934] Trial 30 finished with value: 0.7624952793121338 and parameters: {'temperature': 0.1908024530877909, 'exclusion_radius': 3}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:55,830] Trial 31 finished with value: 0.7855077385902405 and parameters: {'temperature': 0.10715471379313618, 'exclusion_radius': 8}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:57,723] Trial 32 finished with value: 0.7820119857788086 and parameters: {'temperature': 0.09954922176031647, 'exclusion_radius': 11}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 12:59:59,621] Trial 33 finished with value: 0.7816778421401978 and parameters: {'temperature': 0.08327174951539369, 'exclusion_radius': 7}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:01,520] Trial 34 finished with value: 0.7880146503448486 and parameters: {'temperature': 0.1318860160295594, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:03,418] Trial 35 finished with value: 0.7604740858078003 and parameters: {'temperature': 0.12906513895572921, 'exclusion_radius': 12}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:05,319] Trial 36 finished with value: 0.7625692486763 and parameters: {'temperature': 0.14787772190775986, 'exclusion_radius': 14}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:07,216] Trial 37 finished with value: 0.738742470741272 and parameters: {'temperature': 0.23246943177517293, 'exclusion_radius': 10}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:09,190] Trial 38 finished with value: 0.6674429178237915 and parameters: {'temperature': 0.46754210064222784, 'exclusion_radius': 6}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:11,093] Trial 39 finished with value: 0.7293956279754639 and parameters: {'temperature': 0.06856557529640211, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:12,992] Trial 40 finished with value: 0.6963403224945068 and parameters: {'temperature': 0.30823067435877344, 'exclusion_radius': 13}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:14,910] Trial 41 finished with value: 0.7855128645896912 and parameters: {'temperature': 0.08716681853742762, 'exclusion_radius': 9}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:16,840] Trial 42 finished with value: 0.7803674340248108 and parameters: {'temperature': 0.11734016503700856, 'exclusion_radius': 8}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:18,775] Trial 43 finished with value: 0.7488560080528259 and parameters: {'temperature': 0.07484772047963288, 'exclusion_radius': 11}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:20,801] Trial 44 finished with value: 0.7917414307594299 and parameters: {'temperature': 0.09626053785374251, 'exclusion_radius': 6}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:22,830] Trial 45 finished with value: 0.794891357421875 and parameters: {'temperature': 0.12856274979769347, 'exclusion_radius': 4}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:24,877] Trial 46 finished with value: 0.7803632616996765 and parameters: {'temperature': 0.1502836516111319, 'exclusion_radius': 4}. Best is trial 15 with value: 0.8059487342834473.
[I 2026-02-23 13:00:26,932] Trial 47 finished with value: 0.8177174925804138 and parameters: {'temperature': 0.09418251159949012, 'exclusion_radius': 3}. Best is trial 47 with value: 0.8177174925804138.
[I 2026-02-23 13:00:29,014] Trial 48 finished with value: 0.8095493316650391 and parameters: {'temperature': 0.0808414732186732, 'exclusion_radius': 3}. Best is trial 47 with value: 0.8177174925804138.
[I 2026-02-23 13:00:31,116] Trial 49 finished with value: 0.7437108159065247 and parameters: {'temperature': 0.06034182600531251, 'exclusion_radius': 3}. Best is trial 47 with value: 0.8177174925804138.

In [ ]:
# Augmentation stage:

# mask_ratio = trial.suggest_float("mask_ratio", 0.1, 0.4)
# jitter_sigma = trial.suggest_float("jitter_sigma", 0.005, 0.05, log=True)

class AugmentationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        mask_ratio = trial.suggest_float("mask_ratio", hyperparams_config["mask_ratio"][0], hyperparams_config["mask_ratio"][1])
        jitter_sigma = trial.suggest_float("jitter_sigma", hyperparams_config["jitter_sigma"][0], hyperparams_config["jitter_sigma"][1], log=True)

        aug_params = AugmentationParams(mask_ratio, jitter_sigma)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("aug_params", aug_params.__dict__)

        return score
    
study_aug = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="augmentation_stage",
    load_if_exists=True
)
study_aug.optimize(AugmentationStageObjective(data, device, 
                                                     {
      **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"]
}
), n_trials=50)

[I 2026-02-23 14:09:11,185] Using an existing study with name 'augmentation_stage' instead of creating a new one.

[I 2026-02-23 14:09:13,194] Trial 8 finished with value: 0.8583179712295532 and parameters: {'mask_ratio': 0.12665154206769594, 'jitter_sigma': 0.006066175263652591}. Best is trial 4 with value: 0.8638263940811157.
[I 2026-02-23 14:09:15,238] Trial 9 finished with value: 0.7540524005889893 and parameters: {'mask_ratio': 0.3044021721555483, 'jitter_sigma': 0.00809025315220967}. Best is trial 4 with value: 0.8638263940811157.
[I 2026-02-23 14:09:17,212] Trial 10 finished with value: 0.869362473487854 and parameters: {'mask_ratio': 0.10893971080565641, 'jitter_sigma': 0.046956947754562745}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:19,195] Trial 11 finished with value: 0.6780766248703003 and parameters: {'mask_ratio': 0.39139443299241805, 'jitter_sigma': 0.04933521504431264}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:21,171] Trial 12 finished with value: 0.8658281564712524 and parameters: {'mask_ratio': 0.10212459240894632, 'jitter_sigma': 0.011273540851734628}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:23,159] Trial 13 finished with value: 0.8656086921691895 and parameters: {'mask_ratio': 0.10905413096252174, 'jitter_sigma': 0.011945584746844552}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:25,135] Trial 14 finished with value: 0.8143068552017212 and parameters: {'mask_ratio': 0.22430111828734994, 'jitter_sigma': 0.025215259268883156}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:27,112] Trial 15 finished with value: 0.8573607206344604 and parameters: {'mask_ratio': 0.1360179362144681, 'jitter_sigma': 0.010500621654875397}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:29,092] Trial 16 finished with value: 0.7867931127548218 and parameters: {'mask_ratio': 0.255570495622643, 'jitter_sigma': 0.02578682236867026}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:31,083] Trial 17 finished with value: 0.8560664057731628 and parameters: {'mask_ratio': 0.1466487104951107, 'jitter_sigma': 0.009965822932369802}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:33,063] Trial 18 finished with value: 0.8203457593917847 and parameters: {'mask_ratio': 0.20422216819402295, 'jitter_sigma': 0.035478970594490004}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:35,044] Trial 19 finished with value: 0.6835288405418396 and parameters: {'mask_ratio': 0.35112198710391873, 'jitter_sigma': 0.013897098529590654}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:37,025] Trial 20 finished with value: 0.859386146068573 and parameters: {'mask_ratio': 0.1038177297234045, 'jitter_sigma': 0.008774455872924919}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:39,012] Trial 21 finished with value: 0.7711888551712036 and parameters: {'mask_ratio': 0.2554691011303495, 'jitter_sigma': 0.020751413263230368}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:40,997] Trial 22 finished with value: 0.860605001449585 and parameters: {'mask_ratio': 0.10503687307658496, 'jitter_sigma': 0.011806803221476533}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:42,984] Trial 23 finished with value: 0.8578873872756958 and parameters: {'mask_ratio': 0.13029864145890022, 'jitter_sigma': 0.012582983016956062}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:44,969] Trial 24 finished with value: 0.8488789796829224 and parameters: {'mask_ratio': 0.16590275532288118, 'jitter_sigma': 0.010910875423611376}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:46,954] Trial 25 finished with value: 0.8495566844940186 and parameters: {'mask_ratio': 0.12474610449837431, 'jitter_sigma': 0.023404772801716066}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:48,943] Trial 26 finished with value: 0.8252772688865662 and parameters: {'mask_ratio': 0.1905545464751836, 'jitter_sigma': 0.014978170404481262}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:50,930] Trial 27 finished with value: 0.8464872241020203 and parameters: {'mask_ratio': 0.15079046823842027, 'jitter_sigma': 0.007102287550531274}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:52,921] Trial 28 finished with value: 0.8521296977996826 and parameters: {'mask_ratio': 0.11786865910913097, 'jitter_sigma': 0.008975931898551243}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:54,914] Trial 29 finished with value: 0.8222898244857788 and parameters: {'mask_ratio': 0.1853253927858267, 'jitter_sigma': 0.013166709786496504}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:56,910] Trial 30 finished with value: 0.8410329222679138 and parameters: {'mask_ratio': 0.15545525248715564, 'jitter_sigma': 0.019630024616680956}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:09:58,907] Trial 31 finished with value: 0.8478432297706604 and parameters: {'mask_ratio': 0.16604577347836008, 'jitter_sigma': 0.033812001532522236}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:00,907] Trial 32 finished with value: 0.8645460605621338 and parameters: {'mask_ratio': 0.10194925256128899, 'jitter_sigma': 0.01648770185255377}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:02,910] Trial 33 finished with value: 0.8637809753417969 and parameters: {'mask_ratio': 0.10136188474015463, 'jitter_sigma': 0.028670582096972298}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:04,949] Trial 34 finished with value: 0.8517352342605591 and parameters: {'mask_ratio': 0.1392692641860742, 'jitter_sigma': 0.005021515383524551}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:06,948] Trial 35 finished with value: 0.8571112155914307 and parameters: {'mask_ratio': 0.11950761256756473, 'jitter_sigma': 0.017264523823265293}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:08,957] Trial 36 finished with value: 0.805370032787323 and parameters: {'mask_ratio': 0.22992418138551138, 'jitter_sigma': 0.0386941588710361}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:10,961] Trial 37 finished with value: 0.8650918006896973 and parameters: {'mask_ratio': 0.11702359573999137, 'jitter_sigma': 0.011722504851813429}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:12,967] Trial 38 finished with value: 0.769690990447998 and parameters: {'mask_ratio': 0.27435222002828985, 'jitter_sigma': 0.01146561346870773}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:14,972] Trial 39 finished with value: 0.8511554002761841 and parameters: {'mask_ratio': 0.11938660633276243, 'jitter_sigma': 0.009530202126513539}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:16,976] Trial 40 finished with value: 0.836359977722168 and parameters: {'mask_ratio': 0.17819009853672363, 'jitter_sigma': 0.007181301274746567}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:18,979] Trial 41 finished with value: 0.8449137210845947 and parameters: {'mask_ratio': 0.14746595361382486, 'jitter_sigma': 0.014223059058294312}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:20,980] Trial 42 finished with value: 0.8602523803710938 and parameters: {'mask_ratio': 0.10023701119095459, 'jitter_sigma': 0.015532276605091206}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:22,979] Trial 43 finished with value: 0.8687459826469421 and parameters: {'mask_ratio': 0.11495222193218263, 'jitter_sigma': 0.008095014038277365}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:24,976] Trial 44 finished with value: 0.8552858233451843 and parameters: {'mask_ratio': 0.11782473599124155, 'jitter_sigma': 0.008227500153878142}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:26,971] Trial 45 finished with value: 0.8475292325019836 and parameters: {'mask_ratio': 0.13608777678378936, 'jitter_sigma': 0.00774096301082239}. Best is trial 10 with value: 0.869362473487854.
[I 2026-02-23 14:10:28,977] Trial 46 finished with value: 0.872439980506897 and parameters: {'mask_ratio': 0.1153883102823196, 'jitter_sigma': 0.006324426296094188}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:30,972] Trial 47 finished with value: 0.8534262180328369 and parameters: {'mask_ratio': 0.14044604775672512, 'jitter_sigma': 0.0052973826962145545}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:32,966] Trial 48 finished with value: 0.8700022101402283 and parameters: {'mask_ratio': 0.13081139662779415, 'jitter_sigma': 0.0066076179122354795}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:34,960] Trial 49 finished with value: 0.8339843153953552 and parameters: {'mask_ratio': 0.15944510684919805, 'jitter_sigma': 0.006138742873215818}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:36,954] Trial 50 finished with value: 0.8236332535743713 and parameters: {'mask_ratio': 0.1996389013918584, 'jitter_sigma': 0.006283899743646636}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:38,945] Trial 51 finished with value: 0.7214980125427246 and parameters: {'mask_ratio': 0.3415741668503658, 'jitter_sigma': 0.00675022064176949}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:40,936] Trial 52 finished with value: 0.855831503868103 and parameters: {'mask_ratio': 0.13022611398823494, 'jitter_sigma': 0.005526980964781801}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:42,924] Trial 53 finished with value: 0.8670214414596558 and parameters: {'mask_ratio': 0.11188088171696417, 'jitter_sigma': 0.007888139910115144}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:44,915] Trial 54 finished with value: 0.8652488589286804 and parameters: {'mask_ratio': 0.11154703620008674, 'jitter_sigma': 0.007861107623975662}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:46,898] Trial 55 finished with value: 0.8620031476020813 and parameters: {'mask_ratio': 0.13144371768536978, 'jitter_sigma': 0.006401177740662304}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:48,889] Trial 56 finished with value: 0.6317588090896606 and parameters: {'mask_ratio': 0.39941076237044715, 'jitter_sigma': 0.04893777521614399}. Best is trial 46 with value: 0.872439980506897.
[I 2026-02-23 14:10:50,880] Trial 57 finished with value: 0.8394429683685303 and parameters: {'mask_ratio': 0.17357337375870474, 'jitter_sigma': 0.009718170579951897}. Best is trial 46 with value: 0.872439980506897.

In [ ]:
# Optimization stage:

# learning_rate = trial.suggest_float("learning_rate", 1e-4, 3e-3, log=True)
# batch_size = trial.suggest_categorical("batch_size", [32, 64, 128])

class OptimizationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        learning_rate = trial.suggest_float("learning_rate", hyperparams_config["learning_rate"][0], hyperparams_config["learning_rate"][1], log=True)
        batch_size = trial.suggest_categorical("batch_size", hyperparams_config["batch_size"])

        opt_params = OptimizationParams(learning_rate, batch_size)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])
        aug_params = AugmentationParams(self.fixed_params["mask_ratio"], self.fixed_params["jitter_sigma"])

        train_loader = create_loader(self.data, window_size, batch_size)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("opt_params", opt_params.__dict__)

        return score
    
study_opt = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="optimization_stage",
    load_if_exists=True
)
study_opt.optimize(OptimizationStageObjective(data, device,
                                                     {
  **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"],
    **study_aug.best_trial.user_attrs["aug_params"]
}), n_trials=50)

[I 2026-02-23 14:22:07,500] A new study created in RDB with name: optimization_stage

[I 2026-02-23 14:22:09,552] Trial 0 finished with value: 0.8860816955566406 and parameters: {'learning_rate': 0.0024841809279477173, 'batch_size': 64}. Best is trial 0 with value: 0.8860816955566406.
[I 2026-02-23 14:22:12,321] Trial 1 finished with value: 0.8970596194267273 and parameters: {'learning_rate': 0.0016340155948858838, 'batch_size': 32}. Best is trial 1 with value: 0.8970596194267273.
[I 2026-02-23 14:22:14,283] Trial 2 finished with value: 0.7487084865570068 and parameters: {'learning_rate': 0.00011630511430376669, 'batch_size': 64}. Best is trial 1 with value: 0.8970596194267273.
[I 2026-02-23 14:22:16,235] Trial 3 finished with value: 0.8096197247505188 and parameters: {'learning_rate': 0.00031167405254851053, 'batch_size': 64}. Best is trial 1 with value: 0.8970596194267273.
[I 2026-02-23 14:22:18,196] Trial 4 finished with value: 0.7981594204902649 and parameters: {'learning_rate': 0.0002786714268131344, 'batch_size': 64}. Best is trial 1 with value: 0.8970596194267273.
[I 2026-02-23 14:22:20,152] Trial 5 finished with value: 0.8728539943695068 and parameters: {'learning_rate': 0.0013483590967176063, 'batch_size': 64}. Best is trial 1 with value: 0.8970596194267273.
[I 2026-02-23 14:22:22,836] Trial 6 finished with value: 0.9024257063865662 and parameters: {'learning_rate': 0.001957320001027985, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:25,525] Trial 7 finished with value: 0.8891111612319946 and parameters: {'learning_rate': 0.0011699943268295573, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:28,203] Trial 8 finished with value: 0.8111646771430969 and parameters: {'learning_rate': 0.00015370295720035544, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:31,627] Trial 9 finished with value: 0.8043367862701416 and parameters: {'learning_rate': 0.0005891304835540952, 'batch_size': 128}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:34,951] Trial 10 finished with value: 0.8307551741600037 and parameters: {'learning_rate': 0.0007451212160522077, 'batch_size': 128}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:37,714] Trial 11 finished with value: 0.8964473605155945 and parameters: {'learning_rate': 0.002896319040139828, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:40,450] Trial 12 finished with value: 0.899286150932312 and parameters: {'learning_rate': 0.0014655607842956155, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:43,186] Trial 13 finished with value: 0.887702465057373 and parameters: {'learning_rate': 0.0009215572870040649, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:45,931] Trial 14 finished with value: 0.898419201374054 and parameters: {'learning_rate': 0.0019818562778309724, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:48,682] Trial 15 finished with value: 0.861534059047699 and parameters: {'learning_rate': 0.00040593367512311207, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:51,423] Trial 16 finished with value: 0.8967648148536682 and parameters: {'learning_rate': 0.0018647872464137212, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:54,769] Trial 17 finished with value: 0.8431736826896667 and parameters: {'learning_rate': 0.001041634104686667, 'batch_size': 128}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:22:57,535] Trial 18 finished with value: 0.8738967776298523 and parameters: {'learning_rate': 0.0007199424808488586, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:00,286] Trial 19 finished with value: 0.9020150899887085 and parameters: {'learning_rate': 0.00294754327330283, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:03,642] Trial 20 finished with value: 0.8489797115325928 and parameters: {'learning_rate': 0.0023704904301929193, 'batch_size': 128}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:06,430] Trial 21 finished with value: 0.8944677114486694 and parameters: {'learning_rate': 0.0015306672956715754, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:09,182] Trial 22 finished with value: 0.8962066173553467 and parameters: {'learning_rate': 0.0029971400943360296, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:11,918] Trial 23 finished with value: 0.9004831314086914 and parameters: {'learning_rate': 0.0020376182524713877, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:14,687] Trial 24 finished with value: 0.8974486589431763 and parameters: {'learning_rate': 0.0021087069212420363, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:17,444] Trial 25 finished with value: 0.9007672667503357 and parameters: {'learning_rate': 0.0020878160697896646, 'batch_size': 32}. Best is trial 6 with value: 0.9024257063865662.
[I 2026-02-23 14:23:20,197] Trial 26 finished with value: 0.902505099773407 and parameters: {'learning_rate': 0.0028134772742636283, 'batch_size': 32}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:22,925] Trial 27 finished with value: 0.8982059359550476 and parameters: {'learning_rate': 0.0025677017859049244, 'batch_size': 32}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:26,283] Trial 28 finished with value: 0.8518990278244019 and parameters: {'learning_rate': 0.0029814169619230974, 'batch_size': 128}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:29,067] Trial 29 finished with value: 0.8837518095970154 and parameters: {'learning_rate': 0.0009028677785744596, 'batch_size': 32}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:31,059] Trial 30 finished with value: 0.8800298571586609 and parameters: {'learning_rate': 0.0016995070419011367, 'batch_size': 64}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:33,819] Trial 31 finished with value: 0.8961846828460693 and parameters: {'learning_rate': 0.002350211539401793, 'batch_size': 32}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:36,585] Trial 32 finished with value: 0.8950285315513611 and parameters: {'learning_rate': 0.0012711428538896203, 'batch_size': 32}. Best is trial 26 with value: 0.902505099773407.
[I 2026-02-23 14:23:39,345] Trial 33 finished with value: 0.9052321910858154 and parameters: {'learning_rate': 0.0017009936483370917, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:42,078] Trial 34 finished with value: 0.8957255482673645 and parameters: {'learning_rate': 0.0016463213692225595, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:44,061] Trial 35 finished with value: 0.8926116228103638 and parameters: {'learning_rate': 0.002491645492446682, 'batch_size': 64}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:46,825] Trial 36 finished with value: 0.8998894691467285 and parameters: {'learning_rate': 0.0017159793973423852, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:48,811] Trial 37 finished with value: 0.7782487273216248 and parameters: {'learning_rate': 0.00019492878254487463, 'batch_size': 64}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:51,595] Trial 38 finished with value: 0.8947634100914001 and parameters: {'learning_rate': 0.00114421427594553, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:54,354] Trial 39 finished with value: 0.8697802424430847 and parameters: {'learning_rate': 0.0004473924658672225, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:57,090] Trial 40 finished with value: 0.8964216113090515 and parameters: {'learning_rate': 0.001351930623720017, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:23:59,853] Trial 41 finished with value: 0.9020689725875854 and parameters: {'learning_rate': 0.002202100155312956, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:02,588] Trial 42 finished with value: 0.8976069688796997 and parameters: {'learning_rate': 0.0025720702914435547, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:05,344] Trial 43 finished with value: 0.8994856476783752 and parameters: {'learning_rate': 0.002125885346309916, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:08,101] Trial 44 finished with value: 0.898516058921814 and parameters: {'learning_rate': 0.0024867605845452826, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:10,093] Trial 45 finished with value: 0.8775909543037415 and parameters: {'learning_rate': 0.0018280353601067248, 'batch_size': 64}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:12,830] Trial 46 finished with value: 0.9003156423568726 and parameters: {'learning_rate': 0.0014899237387835098, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:16,201] Trial 47 finished with value: 0.8551022410392761 and parameters: {'learning_rate': 0.002840022488278692, 'batch_size': 128}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:18,985] Trial 48 finished with value: 0.8497588634490967 and parameters: {'learning_rate': 0.0003098071471277275, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.
[I 2026-02-23 14:24:21,724] Trial 49 finished with value: 0.8870978355407715 and parameters: {'learning_rate': 0.00101542189905376, 'batch_size': 32}. Best is trial 33 with value: 0.9052321910858154.

In [ ]:
from datetime import datetime

class TS2VecHyperparameterPipeline:
    def __init__(self, data, device, mode="long_term"):
        self.data = data
        self.device = device
        self.results = {}
        self.mode = mode  # "long_term" or "short_term"

    def _run_stage(self, name, objective_cls, fixed_params, n_trials, result_key, attr_key):
        study = optuna.create_study(
            direction="maximize",
            sampler=optuna.samplers.TPESampler(),
            storage="sqlite:///ts2vec_hpo.db",
            study_name=f"{name}_stage_{self.mode}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            load_if_exists=True,
        )
        study.optimize(objective_cls(self.data, self.device, fixed_params), n_trials=n_trials)
        self.results[result_key] = study.best_trial.user_attrs[attr_key]

    def run(self):
        self._run_stage(
            "window",
            WindowStageObjective,
            {},
            n_trials=7,
            result_key="window",
            attr_key="window_params",
        )
        self._run_stage(
            "arch",
            ArchitectureStageObjective,
            self.results["window"],
            n_trials=30,
            result_key="architecture",
            attr_key="arch_params",
        )
        self._run_stage(
            "contrastive",
            ContrastiveStageObjective,
            {**self.results["window"], **self.results["architecture"]},
            n_trials=50,
            result_key="contrastive",
            attr_key="contrastive_params",
        )
        self._run_stage(
            "augmentation",
            AugmentationStageObjective,
            {**self.results["window"], **self.results["architecture"], **self.results["contrastive"]},
            n_trials=50,
            result_key="augmentation",
            attr_key="aug_params",
        )
        self._run_stage(
            "optimization",
            OptimizationStageObjective,
            {
                **self.results["window"],
                **self.results["architecture"],
                **self.results["contrastive"],
                **self.results["augmentation"],
            },
            n_trials=50,
            result_key="optimization",
            attr_key="opt_params",
        )
        return self.results

# Run the pipeline
pipeline = TS2VecHyperparameterPipeline(data, device, mode="long_term")
final_results = pipeline.run()
print(final_results)

In [ ]:
# train final model with best hyperparameters

best_model_params = {
    **final_results["window"],
    **final_results["architecture"],
    **final_results["contrastive"],
    **final_results["augmentation"],
    **final_results["optimization"]
}

In [33]:
# list all the best parameters from each stage
param_summary = {
    "window": 60,
    "architecture": study_arch.best_trial.user_attrs["arch_params"],
    "contrastive": study_contrastive.best_trial.user_attrs["contrastive_params"],
    "augmentation": study_aug.best_trial.user_attrs["aug_params"],
    "optimization": study_opt.best_trial.user_attrs["opt_params"]
}

```json
{'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 4},
 'contrastive': {'temperature': 0.10901392823581604, 'exclusion_radius': 18},
 'augmentation': {'mask_ratio': 0.10112014206194599,
  'jitter_sigma': 0.019884546877356246},
 'optimization': {'learning_rate': 0.0012543308801674451, 'batch_size': 64}}
```
```json
{'window': 60,
 'architecture': {'hidden_dim': 128, 'num_layers': 4},
 'contrastive': {'temperature': 0.09418251159949012, 'exclusion_radius': 3},
 'augmentation': {'mask_ratio': 0.1153883102823196,
  'jitter_sigma': 0.006324426296094188},
 'optimization': {'learning_rate': 0.0017009936483370917, 'batch_size': 32}}
```

In [34]:
param_summary

{'window': 60,
 'architecture': {'hidden_dim': 128, 'num_layers': 4},
 'contrastive': {'temperature': 0.09418251159949012, 'exclusion_radius': 3},
 'augmentation': {'mask_ratio': 0.1153883102823196,
  'jitter_sigma': 0.006324426296094188},
 'optimization': {'learning_rate': 0.0017009936483370917, 'batch_size': 32}}