In [1]:
from torch.utils.data import Dataset, DataLoader
import torch
import pandas as pd
import numpy as np
import pickle

In [2]:
device ="mps"

In [3]:
with open('../../data/complete_features.pkl', 'rb') as f:
    all_data = pickle.load(f)

In [4]:
data = all_data["scaled_featured"].copy()
data["close"] = all_data["Close"]

In [5]:
# log returns
data["log_return"] = np.log(data["close"] / data["close"].shift(1))
data.dropna(inplace=True)

In [6]:
data

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20,close,log_return
Date,,,,,,,,,,,,,,
2008-07-08,-1.211754,-1.882225,2.077736,-0.022097,-1.117078,-1.046961,-0.542321,-2.455523,1.450259,0.981827,-2.206775,-0.513460,3988.550049,-0.010339
2008-07-09,-0.957426,-1.882225,2.289506,1.636228,-1.218247,-0.338846,-0.561373,-1.988903,1.476862,0.785786,-1.960992,-0.565134,4157.100098,0.041390
2008-07-10,-0.975703,-1.882225,2.287995,-0.006124,-1.013921,-0.474801,-0.596656,-2.401313,1.493754,0.505013,-1.940271,-0.562557,4162.200195,0.001226
2008-07-11,-1.136144,-1.882225,2.391761,0.804554,-1.050675,-0.396400,-0.475448,-2.987661,1.507027,0.400347,-2.078101,-0.510752,4049.000000,-0.027574
2008-07-14,-1.257924,-1.882225,2.371776,-0.148393,-1.268721,-0.518601,-0.436624,-3.173512,1.521334,0.430252,-2.071028,-0.455743,4039.699951,-0.002300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-15,0.375855,0.654743,-0.795604,0.021503,0.541634,-0.126723,-0.727148,-1.189892,-0.988672,-0.309058,0.314003,0.507783,25069.199219,-0.001785
2025-09-16,0.280399,0.654743,-0.833663,-0.287568,0.045456,-0.238463,-0.708679,-1.276291,-1.000565,-0.327333,0.453848,0.513354,25239.099609,0.006754
2025-09-17,0.260114,0.654743,-0.836851,-0.019044,0.154682,-0.363408,-0.703390,-1.335486,-1.009414,-0.239281,0.522324,0.511624,25330.250000,0.003605
2025-09-18,0.293060,0.654743,-0.832619,0.038097,0.230366,-0.508229,-0.737254,-1.044970,-1.020331,-0.299090,0.591810,0.309460,25423.599609,0.003679
2025-09-19,0.080198,0.654743,-0.823297,0.077298,0.164701,-0.717435,-0.742174,-1.146226,-1.028834,-0.229313,0.500421,0.283359,25327.050781,-0.003805

In [7]:
close = data["close"]
log_return = data["log_return"]

In [8]:
data.shape

(4218, 14)

In [9]:
data.drop(columns=["close","log_return"], inplace=True)

In [10]:
data

,rolling_sharpe_20,rolling_max_dd_60,realized_vol_20,vol_slope_20,autocorr_20,rel_spx_20,usdinr_vol_20,rel_gold_20,vix_level_20,vix_slope_20,trend_strength_200,sector_dispersion_ratio_20
Date,,,,,,,,,,,,
2008-07-08,-1.211754,-1.882225,2.077736,-0.022097,-1.117078,-1.046961,-0.542321,-2.455523,1.450259,0.981827,-2.206775,-0.513460
2008-07-09,-0.957426,-1.882225,2.289506,1.636228,-1.218247,-0.338846,-0.561373,-1.988903,1.476862,0.785786,-1.960992,-0.565134
2008-07-10,-0.975703,-1.882225,2.287995,-0.006124,-1.013921,-0.474801,-0.596656,-2.401313,1.493754,0.505013,-1.940271,-0.562557
2008-07-11,-1.136144,-1.882225,2.391761,0.804554,-1.050675,-0.396400,-0.475448,-2.987661,1.507027,0.400347,-2.078101,-0.510752
2008-07-14,-1.257924,-1.882225,2.371776,-0.148393,-1.268721,-0.518601,-0.436624,-3.173512,1.521334,0.430252,-2.071028,-0.455743
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-15,0.375855,0.654743,-0.795604,0.021503,0.541634,-0.126723,-0.727148,-1.189892,-0.988672,-0.309058,0.314003,0.507783
2025-09-16,0.280399,0.654743,-0.833663,-0.287568,0.045456,-0.238463,-0.708679,-1.276291,-1.000565,-0.327333,0.453848,0.513354
2025-09-17,0.260114,0.654743,-0.836851,-0.019044,0.154682,-0.363408,-0.703390,-1.335486,-1.009414,-0.239281,0.522324,0.511624
2025-09-18,0.293060,0.654743,-0.832619,0.038097,0.230366,-0.508229,-0.737254,-1.044970,-1.020331,-0.299090,0.591810,0.309460
2025-09-19,0.080198,0.654743,-0.823297,0.077298,0.164701,-0.717435,-0.742174,-1.146226,-1.028834,-0.229313,0.500421,0.283359

In [11]:
class TimeSeriesWindowDataset(Dataset):
    def __init__(self, data, window_size=60):
        """
        data: numpy array [T, D]
        """
        self.data = torch.tensor(data, dtype=torch.float32)
        self.window_size = window_size

    def __len__(self):
        return len(self.data) - self.window_size + 1

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.window_size]
        return x

window_size = 60
val_size = 0

train_size = int(len(data) * (1 - val_size))
train_data = data.iloc[:train_size]
val_data = data.iloc[train_size:]

train_dataset = TimeSeriesWindowDataset(train_data.values, window_size)
val_dataset = TimeSeriesWindowDataset(val_data.values, window_size)
combined_dataset = TimeSeriesWindowDataset(data.values, window_size)

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
combined_loader = DataLoader(combined_dataset, batch_size=batch_size, shuffle=False)

In [12]:
import torch.nn as nn
import torch.nn.functional as F

class TS2VecModel(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, num_layers=5):
        super(TS2VecModel, self).__init__()
        layers = []
        for i in range(num_layers):
            dilation = 2 ** i
            layers.append(nn.Conv1d(input_dim if i == 0 else hidden_dim, hidden_dim, kernel_size=3, padding=dilation, dilation=dilation))
            layers.append(nn.ReLU())
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        # x: [B, T, D]
        x = x.permute(0, 2, 1)  # [B, D, T]
        x = self.network(x)     # [B, H, T]
        x = x.permute(0, 2, 1)  # [B, T, H]
        # normalize
        x = F.normalize(x, p=2, dim=-1)
        return x
    
model = TS2VecModel(input_dim=data.shape[1], hidden_dim=128, num_layers=6).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [13]:
def time_mask(x, mask_ratio=0.2):
    B, T, D = x.shape
    mask_len = int(T * mask_ratio)
    start = np.random.randint(0, T - mask_len)
    x = x.clone()
    x[:, start:start+mask_len, :] = 0
    return x


def jitter(x, sigma=0.02):
    return x + sigma * torch.randn_like(x)


def temporal_pooling(z):
    if z.size(1) % 2 == 1:
        z = z[:, :-1]
    return z.reshape(z.size(0), z.size(1)//2, 2, z.size(2)).mean(dim=2)


def ts2vec_contrastive_loss_vectorized(
    z1, z2,
    temperature=0.1,
    base_exclusion_radius=5
):
    """
    z1, z2: [B, T, C]
    """
    B, T, C = z1.shape
    device = z1.device

    # flatten (instance, time)
    z1_flat = z1.reshape(B*T, C)
    z2_flat = z2.reshape(B*T, C)

    # cosine similarity == dot product because embeddings are normalized
    sim = torch.matmul(z1_flat, z2_flat.T) / temperature   # [BT, BT]

    # ----- temporal negative mask -----
    exclusion_radius = min(base_exclusion_radius, (T - 1) // 2)

    if exclusion_radius == 0:
        return torch.tensor(0.0, device=device)

    # time index per row
    time_idx = torch.arange(T, device=device).repeat(B)     # [BT]

    # batch index per row
    batch_idx = torch.arange(B, device=device).repeat_interleave(T)

    # same batch & temporally close → mask out
    temporal_dist = torch.abs(time_idx[:, None] - time_idx[None, :])
    same_batch = batch_idx[:, None] == batch_idx[None, :]

    invalid_negatives = same_batch & (temporal_dist <= exclusion_radius)

    # allow diagonal (positive pairs)
    diag = torch.eye(B*T, device=device, dtype=torch.bool)
    invalid_negatives = invalid_negatives & (~diag)

    # mask invalid negatives
    sim = sim.masked_fill(invalid_negatives, -1e9)

    # positives are diagonal
    labels = torch.arange(B*T, device=device)

    return F.cross_entropy(sim, labels)



def hierarchical_ts2vec_loss_v2(
    z1, z2,
    temperature=0.1,
    exclusion_radius=5,
    min_time=2
):
    total_loss = 0.0
    depth = 0

    while z1.size(1) >= min_time:
        T = z1.size(1)

        if T > 2 * exclusion_radius + 1:
            total_loss += ts2vec_contrastive_loss_vectorized(
                z1, z2,
                temperature,
                exclusion_radius
            )
            depth += 1

        z1 = temporal_pooling(z1)
        z2 = temporal_pooling(z2)

    return total_loss / max(depth, 1)

In [14]:
def temporal_contrast_score(Z, k=20):
    """
    This function computes the temporal contrast score for a given set of embeddings Z.
    Z: [T, C] numpy array of embeddings
    k: temporal gap for negative pairs
    """
    pos = []
    neg = []
    
    for i in range(len(Z) - k - 1):
        pos.append(np.dot(Z[i], Z[i+1]))
        neg.append(np.dot(Z[i], Z[i+k]))
    
    return np.mean(pos) - np.mean(neg)

# score = temporal_contrast_score(embeddings_full)
def temporal_contrast_score_multi(Z, pos_gap=1, neg_gaps=(10,20,40)):
    pos = []
    neg = []

    for i in range(len(Z) - max(neg_gaps) - 1):
        pos.append(np.dot(Z[i], Z[i+pos_gap]))
        for k in neg_gaps:
            neg.append(np.dot(Z[i], Z[i+k]))

    return np.mean(pos) - np.mean(neg)


from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

def predictive_score(Z, forward_returns):
    X = Z[:-1]
    y = forward_returns[1:]

    model = Ridge(alpha=1.0)
    model.fit(X, y)
    y_pred = model.predict(X)

    return r2_score(y, y_pred)

In [15]:
from dataclasses import dataclass

@dataclass
class WindowParams:
    window_size: int

@dataclass
class ArchitectureParams:
    hidden_dim: int
    num_layers: int

@dataclass
class ContrastiveParams:
    temperature: float
    exclusion_radius: int

@dataclass
class AugmentationParams:
    mask_ratio: float
    jitter_sigma: float

@dataclass
class OptimizationParams:
    learning_rate: float
    batch_size: int

In [34]:

long={'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 4},
 'contrastive': {'temperature': 0.10901392823581604, 'exclusion_radius': 18},
 'augmentation': {'mask_ratio': 0.10112014206194599,
  'jitter_sigma': 0.019884546877356246},
 'optimization': {'learning_rate': 0.0012543308801674451, 'batch_size': 64}}


short = {'window': 60,
 'architecture': {'hidden_dim': 128, 'num_layers': 4},
 'contrastive': {'temperature': 0.09418251159949012, 'exclusion_radius': 3},
 'augmentation': {'mask_ratio': 0.1153883102823196,
  'jitter_sigma': 0.006324426296094188},
 'optimization': {'learning_rate': 0.0017009936483370917, 'batch_size': 32}}



long_term_model_hyperparams_config = {
    "window_size": [30, 180, 30],  # range for window size  
    "hidden_dim": [ 128, 256,512],    
    "num_layers": [3, 10],
    "temperature": [0.05, 0.5],
    "exclusion_radius": [2, 20],
    "mask_ratio": [0.1, 0.5],
    "jitter_sigma": [0.005, 0.05],
    "learning_rate": [1e-4, 3e-3],
    "batch_size": [32,64,128]
}

short_term_model_hyperparams_config = {
    "window_size": [40, 80, 20],  # range for window size
    "hidden_dim": [32, 64, 128],
    "num_layers": [2, 7],
    "temperature": [0.05, 0.5],
    "exclusion_radius": [1, 5],
    "mask_ratio": [0.1, 0.5],
    "jitter_sigma": [0.005, 0.05],
    "learning_rate": [1e-4, 3e-3],
    "batch_size": [16,32,64]
}

mode = "long_term"  # or "short_term"

if mode == "long_term":
    hyperparams_config = long_term_model_hyperparams_config
else:
    hyperparams_config = short_term_model_hyperparams_config

In [35]:
import optuna
import torch
import numpy as np

class BaseTS2VecObjective:
    def __init__(self, data, device, fixed_params):
        self.data = data
        self.device = device
        self.fixed_params = fixed_params  # dict of params from previous stages

    def build_model(self, arch_params):
        return TS2VecModel(
            input_dim=self.data.shape[1],
            hidden_dim=arch_params.hidden_dim,
            num_layers=arch_params.num_layers
        ).to(self.device)

    def compute_score(self, model):
        model.eval()
        with torch.no_grad():
            full_tensor = torch.tensor(self.data.values, dtype=torch.float32).unsqueeze(0).to(self.device)
            z = model(full_tensor).squeeze(0).cpu().numpy()
            # use forward returns for predictive score
            return predictive_score(z, log_return.values)

    def train_model(self, model, train_loader, contrastive_params, aug_params, opt_params, epochs=3):
        optimizer = torch.optim.Adam(model.parameters(), lr=opt_params.learning_rate)

        model.train()
        for _ in range(epochs):  # small epochs for HPO
            for x in train_loader:
                x = x.to(self.device)
                x1 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)
                x2 = jitter(time_mask(x, aug_params.mask_ratio), aug_params.jitter_sigma)

                z1 = model(x1)
                z2 = model(x2)

                loss = hierarchical_ts2vec_loss_v2(
                    z1, z2,
                    temperature=contrastive_params.temperature,
                    exclusion_radius=contrastive_params.exclusion_radius
                )

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
        return model

In [36]:
def create_loader(data, window_size, batch_size):
    dataset = TimeSeriesWindowDataset(data.values, window_size)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [37]:

class WindowStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):
        window_size = trial.suggest_int("window_size", hyperparams_config["window_size"][0] , hyperparams_config["window_size"][1], step=hyperparams_config["window_size"][2])

        window_params = WindowParams(window_size)

        train_loader = create_loader(self.data, window_size, batch_size=64)

        # fixed architecture for stage 0
        arch_params = ArchitectureParams(hidden_dim=128, num_layers=5)
        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("window_params", window_params.__dict__)

        return score

In [38]:
type(data.values)

numpy.ndarray

In [39]:
study_window = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="window_stage",
    load_if_exists=True
)

# suggest optimal trail count based on combination of parameters 


study_window.optimize(WindowStageObjective(data, device, {}), n_trials=7)

[I 2026-02-27 18:00:08,211] A new study created in RDB with name: window_stage
[I 2026-02-27 18:00:12,674] Trial 0 finished with value: 0.050904186416149466 and parameters: {'window_size': 90}. Best is trial 0 with value: 0.050904186416149466.
[I 2026-02-27 18:00:14,331] Trial 1 finished with value: 0.042956159312403486 and parameters: {'window_size': 30}. Best is trial 0 with value: 0.050904186416149466.
[I 2026-02-27 18:00:29,307] Trial 2 finished with value: 0.05436669860978349 and parameters: {'window_size': 180}. Best is trial 2 with value: 0.05436669860978349.
[I 2026-02-27 18:00:36,844] Trial 3 finished with value: 0.04943881063751843 and parameters: {'window_size': 120}. Best is trial 2 with value: 0.05436669860978349.
[I 2026-02-27 18:00:38,963] Trial 4 finished with value: 0.04542773359364405 and parameters: {'window_size': 60}. Best is trial 2 with value: 0.05436669860978349.
[I 2026-02-27 18:00:40,372] Trial 5 finished with value: 0.050687018414122376 and parameters: {'window_size': 30}. Best is trial 2 with value: 0.05436669860978349.
[I 2026-02-27 18:00:54,997] Trial 6 finished with value: 0.05510604551901488 and parameters: {'window_size': 180}. Best is trial 6 with value: 0.05510604551901488.

In [40]:
study_window.best_trial.user_attrs["window_params"]

{'window_size': 180}

In [41]:
class ArchitectureStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        hidden_dim = trial.suggest_categorical("hidden_dim", hyperparams_config["hidden_dim"])
        num_layers = trial.suggest_int("num_layers", hyperparams_config["num_layers"][0], hyperparams_config["num_layers"][1])

        arch_params = ArchitectureParams(hidden_dim, num_layers)

        window_size = self.fixed_params["window_size"]

        train_loader = create_loader(self.data, window_size, batch_size=64)

        contrastive_params = ContrastiveParams(0.1, 5)
        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("arch_params", arch_params.__dict__)

        return score
    
#!/usr/bin/env python
import os

# Delete the existing study to avoid "dynamic value space" error
if os.path.exists("ts2vec_hpo.db"):
    try:
        optuna.delete_study(study_name="arch_stage", storage="sqlite:///ts2vec_hpo.db")
    except:
        pass

study_arch = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="arch_stage",
    load_if_exists=True
)


study_arch.optimize(ArchitectureStageObjective(data, device, {**study_window.best_trial.user_attrs["window_params"]} ), n_trials= 30)

[I 2026-02-27 18:01:20,401] A new study created in RDB with name: arch_stage
[I 2026-02-27 18:01:34,643] Trial 0 finished with value: 0.06108141168901726 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 0 with value: 0.06108141168901726.
[I 2026-02-27 18:01:48,681] Trial 1 finished with value: 0.0620859089728103 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 1 with value: 0.0620859089728103.
[I 2026-02-27 18:02:03,520] Trial 2 finished with value: 0.0496431994407468 and parameters: {'hidden_dim': 128, 'num_layers': 7}. Best is trial 1 with value: 0.0620859089728103.
[I 2026-02-27 18:02:18,113] Trial 3 finished with value: 0.059232582800011535 and parameters: {'hidden_dim': 128, 'num_layers': 4}. Best is trial 1 with value: 0.0620859089728103.
[I 2026-02-27 18:03:05,487] Trial 4 finished with value: 0.05454666849887868 and parameters: {'hidden_dim': 512, 'num_layers': 10}. Best is trial 1 with value: 0.0620859089728103.
[I 2026-02-27 18:03:30,954] Trial 5 finished with value: 0.0643377891129272 and parameters: {'hidden_dim': 256, 'num_layers': 5}. Best is trial 5 with value: 0.0643377891129272.
[I 2026-02-27 18:03:57,497] Trial 6 finished with value: 0.048354809607268234 and parameters: {'hidden_dim': 256, 'num_layers': 7}. Best is trial 5 with value: 0.0643377891129272.
[I 2026-02-27 18:04:15,447] Trial 7 finished with value: 0.06475383813702962 and parameters: {'hidden_dim': 128, 'num_layers': 3}. Best is trial 7 with value: 0.06475383813702962.
[I 2026-02-27 18:04:51,563] Trial 8 finished with value: 0.07528803686513941 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 8 with value: 0.07528803686513941.
[I 2026-02-27 18:05:08,974] Trial 9 finished with value: 0.04000795853398553 and parameters: {'hidden_dim': 128, 'num_layers': 7}. Best is trial 8 with value: 0.07528803686513941.
[I 2026-02-27 18:05:52,800] Trial 10 finished with value: 0.06187390155164796 and parameters: {'hidden_dim': 512, 'num_layers': 9}. Best is trial 8 with value: 0.07528803686513941.
[I 2026-02-27 18:06:25,313] Trial 11 finished with value: 0.07331330187379614 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 8 with value: 0.07528803686513941.
[I 2026-02-27 18:06:56,488] Trial 12 finished with value: 0.07804434258076154 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:07:27,839] Trial 13 finished with value: 0.06699913828350978 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:08:00,829] Trial 14 finished with value: 0.06512762092358704 and parameters: {'hidden_dim': 512, 'num_layers': 6}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:08:33,798] Trial 15 finished with value: 0.05883007143740837 and parameters: {'hidden_dim': 512, 'num_layers': 6}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:09:11,201] Trial 16 finished with value: 0.06552762717891003 and parameters: {'hidden_dim': 512, 'num_layers': 8}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:09:39,732] Trial 17 finished with value: 0.06778981005292584 and parameters: {'hidden_dim': 512, 'num_layers': 4}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:09:58,420] Trial 18 finished with value: 0.06696599908106748 and parameters: {'hidden_dim': 256, 'num_layers': 4}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:10:31,511] Trial 19 finished with value: 0.05866297095313189 and parameters: {'hidden_dim': 512, 'num_layers': 6}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:11:02,266] Trial 20 finished with value: 0.07569187173393666 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:11:32,970] Trial 21 finished with value: 0.0779650809940543 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:12:01,392] Trial 22 finished with value: 0.0722978989201446 and parameters: {'hidden_dim': 512, 'num_layers': 4}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:12:31,954] Trial 23 finished with value: 0.07245508219737529 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:13:04,656] Trial 24 finished with value: 0.05987071164063573 and parameters: {'hidden_dim': 512, 'num_layers': 6}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:13:23,130] Trial 25 finished with value: 0.06133862891309638 and parameters: {'hidden_dim': 256, 'num_layers': 4}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:14:00,041] Trial 26 finished with value: 0.05525821242368767 and parameters: {'hidden_dim': 512, 'num_layers': 8}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:14:30,446] Trial 27 finished with value: 0.07789455941623102 and parameters: {'hidden_dim': 512, 'num_layers': 5}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:15:03,281] Trial 28 finished with value: 0.05846798490692007 and parameters: {'hidden_dim': 512, 'num_layers': 6}. Best is trial 12 with value: 0.07804434258076154.
[I 2026-02-27 18:15:21,181] Trial 29 finished with value: 0.08719266201005271 and parameters: {'hidden_dim': 256, 'num_layers': 3}. Best is trial 29 with value: 0.08719266201005271.

In [42]:
# Contrastive stage:

# temperature = trial.suggest_float("temperature", 0.05, 0.5, log=True)
# exclusion_radius = trial.suggest_int("exclusion_radius", 2, 20)

class ContrastiveStageObjective(BaseTS2VecObjective):

    def __call__(self, trial):

        temperature = trial.suggest_float("temperature", hyperparams_config["temperature"][0], hyperparams_config["temperature"][1], log=True)
        exclusion_radius = trial.suggest_int("exclusion_radius", hyperparams_config["exclusion_radius"][0], hyperparams_config["exclusion_radius"][1])

        contrastive_params = ContrastiveParams(temperature, exclusion_radius)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        aug_params = AugmentationParams(0.2, 0.02)
        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("contrastive_params", contrastive_params.__dict__)

        return score
    
study_contrastive = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="contrastive_stage",
    load_if_exists=True
)

study_contrastive.optimize(ContrastiveStageObjective(data, device, 
                                                     {
    **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"]
}
), n_trials=50)

[I 2026-02-27 18:19:21,568] A new study created in RDB with name: contrastive_stage
[I 2026-02-27 18:19:38,462] Trial 0 finished with value: 0.07622515662826701 and parameters: {'temperature': 0.12843987805219234, 'exclusion_radius': 16}. Best is trial 0 with value: 0.07622515662826701.
[I 2026-02-27 18:19:55,416] Trial 1 finished with value: 0.07346426298509412 and parameters: {'temperature': 0.1198879184555883, 'exclusion_radius': 9}. Best is trial 0 with value: 0.07622515662826701.
[I 2026-02-27 18:20:12,417] Trial 2 finished with value: 0.03337804235606645 and parameters: {'temperature': 0.25097782258054363, 'exclusion_radius': 5}. Best is trial 0 with value: 0.07622515662826701.
[I 2026-02-27 18:20:29,502] Trial 3 finished with value: 0.081651982700782 and parameters: {'temperature': 0.1015637747023826, 'exclusion_radius': 5}. Best is trial 3 with value: 0.081651982700782.
[I 2026-02-27 18:20:46,624] Trial 4 finished with value: 0.04119563418671501 and parameters: {'temperature': 0.25336957887752826, 'exclusion_radius': 14}. Best is trial 3 with value: 0.081651982700782.
[I 2026-02-27 18:21:04,169] Trial 5 finished with value: 0.10549020229598793 and parameters: {'temperature': 0.05832836187839965, 'exclusion_radius': 3}. Best is trial 5 with value: 0.10549020229598793.
[I 2026-02-27 18:21:21,532] Trial 6 finished with value: 0.06275865273336567 and parameters: {'temperature': 0.11062197444394177, 'exclusion_radius': 3}. Best is trial 5 with value: 0.10549020229598793.
[I 2026-02-27 18:21:38,996] Trial 7 finished with value: 0.0345512690189439 and parameters: {'temperature': 0.28585089296209243, 'exclusion_radius': 12}. Best is trial 5 with value: 0.10549020229598793.
[I 2026-02-27 18:21:57,327] Trial 8 finished with value: 0.1164679629549561 and parameters: {'temperature': 0.07056589516032234, 'exclusion_radius': 11}. Best is trial 8 with value: 0.1164679629549561.
[I 2026-02-27 18:22:16,428] Trial 9 finished with value: 0.036602477581965775 and parameters: {'temperature': 0.4255098145943118, 'exclusion_radius': 11}. Best is trial 8 with value: 0.1164679629549561.
[I 2026-02-27 18:22:35,793] Trial 10 finished with value: 0.12269513277293687 and parameters: {'temperature': 0.06295392144086782, 'exclusion_radius': 19}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:22:55,178] Trial 11 finished with value: 0.11772063721674164 and parameters: {'temperature': 0.053266516125153165, 'exclusion_radius': 20}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:23:14,362] Trial 12 finished with value: 0.11025687691044006 and parameters: {'temperature': 0.05194460113877662, 'exclusion_radius': 20}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:23:33,262] Trial 13 finished with value: 0.09883094908416257 and parameters: {'temperature': 0.07649386133560572, 'exclusion_radius': 20}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:23:51,999] Trial 14 finished with value: 0.10835206289154375 and parameters: {'temperature': 0.07893392194034746, 'exclusion_radius': 17}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:24:10,480] Trial 15 finished with value: 0.06011933395328317 and parameters: {'temperature': 0.16422464214966043, 'exclusion_radius': 18}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:24:28,774] Trial 16 finished with value: 0.11173988631987342 and parameters: {'temperature': 0.05029361578236006, 'exclusion_radius': 15}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:24:47,133] Trial 17 finished with value: 0.04811122414980873 and parameters: {'temperature': 0.1821244162213908, 'exclusion_radius': 18}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:25:05,487] Trial 18 finished with value: 0.09392825728002407 and parameters: {'temperature': 0.08593836089693155, 'exclusion_radius': 20}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:25:23,760] Trial 19 finished with value: 0.12230995940981937 and parameters: {'temperature': 0.07098683043215234, 'exclusion_radius': 13}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:25:41,914] Trial 20 finished with value: 0.09400686677606673 and parameters: {'temperature': 0.06633064039851536, 'exclusion_radius': 8}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:26:00,006] Trial 21 finished with value: 0.10539647711705458 and parameters: {'temperature': 0.08818737070361704, 'exclusion_radius': 14}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:26:17,859] Trial 22 finished with value: 0.10958364146796662 and parameters: {'temperature': 0.060212410580068876, 'exclusion_radius': 17}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:26:35,704] Trial 23 finished with value: 0.10784988310018895 and parameters: {'temperature': 0.06349270471570245, 'exclusion_radius': 13}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:26:53,548] Trial 24 finished with value: 0.10402565543498754 and parameters: {'temperature': 0.05061906429294897, 'exclusion_radius': 18}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:27:11,539] Trial 25 finished with value: 0.08188591668767864 and parameters: {'temperature': 0.09408666285615916, 'exclusion_radius': 9}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:27:29,343] Trial 26 finished with value: 0.061757824002713346 and parameters: {'temperature': 0.13235538305604785, 'exclusion_radius': 19}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:27:47,126] Trial 27 finished with value: 0.0986440414731572 and parameters: {'temperature': 0.07223713035679767, 'exclusion_radius': 16}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:28:04,891] Trial 28 finished with value: 0.11296261924763018 and parameters: {'temperature': 0.05881426093709897, 'exclusion_radius': 16}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:28:22,631] Trial 29 finished with value: 0.07069717346274618 and parameters: {'temperature': 0.13141033382602324, 'exclusion_radius': 15}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:28:40,342] Trial 30 finished with value: 0.053509857703496144 and parameters: {'temperature': 0.19709118098688314, 'exclusion_radius': 19}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:28:58,022] Trial 31 finished with value: 0.1226344281454097 and parameters: {'temperature': 0.07187943027347996, 'exclusion_radius': 11}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:29:15,936] Trial 32 finished with value: 0.1017237264626466 and parameters: {'temperature': 0.0811818732618471, 'exclusion_radius': 9}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:29:34,181] Trial 33 finished with value: 0.08067950323247763 and parameters: {'temperature': 0.10152147626631644, 'exclusion_radius': 7}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:29:52,116] Trial 34 finished with value: 0.1071656473344601 and parameters: {'temperature': 0.06784580808721165, 'exclusion_radius': 12}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:30:09,835] Trial 35 finished with value: 0.08550523354429918 and parameters: {'temperature': 0.1093034889114358, 'exclusion_radius': 6}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:30:27,547] Trial 36 finished with value: 0.09531778259175194 and parameters: {'temperature': 0.05633686934077516, 'exclusion_radius': 10}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:30:45,075] Trial 37 finished with value: 0.11517244024293283 and parameters: {'temperature': 0.09317350309885568, 'exclusion_radius': 13}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:31:02,779] Trial 38 finished with value: 0.09925990472049362 and parameters: {'temperature': 0.06242523322048797, 'exclusion_radius': 10}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:31:20,272] Trial 39 finished with value: 0.029541708808194733 and parameters: {'temperature': 0.48389804484644333, 'exclusion_radius': 14}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:31:37,758] Trial 40 finished with value: 0.12252056613796725 and parameters: {'temperature': 0.07356479512178815, 'exclusion_radius': 12}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:31:55,221] Trial 41 finished with value: 0.09593041242350997 and parameters: {'temperature': 0.07676785731070251, 'exclusion_radius': 12}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:32:12,911] Trial 42 finished with value: 0.10105263379043061 and parameters: {'temperature': 0.055634383665514896, 'exclusion_radius': 2}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:32:30,533] Trial 43 finished with value: 0.09396660259569112 and parameters: {'temperature': 0.07243041426230833, 'exclusion_radius': 10}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:32:47,968] Trial 44 finished with value: 0.11402963513549669 and parameters: {'temperature': 0.06784586572813732, 'exclusion_radius': 13}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:33:05,402] Trial 45 finished with value: 0.09649467399758993 and parameters: {'temperature': 0.10192995696328482, 'exclusion_radius': 12}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:33:22,838] Trial 46 finished with value: 0.07711173009675931 and parameters: {'temperature': 0.11950591708361707, 'exclusion_radius': 19}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:33:40,258] Trial 47 finished with value: 0.035699734066651057 and parameters: {'temperature': 0.37003854525149904, 'exclusion_radius': 15}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:33:57,675] Trial 48 finished with value: 0.10897159144895818 and parameters: {'temperature': 0.054460513087545306, 'exclusion_radius': 11}. Best is trial 10 with value: 0.12269513277293687.
[I 2026-02-27 18:34:15,075] Trial 49 finished with value: 0.11366264396410741 and parameters: {'temperature': 0.08319176205861685, 'exclusion_radius': 17}. Best is trial 10 with value: 0.12269513277293687.

In [43]:
# Augmentation stage:

# mask_ratio = trial.suggest_float("mask_ratio", 0.1, 0.4)
# jitter_sigma = trial.suggest_float("jitter_sigma", 0.005, 0.05, log=True)

class AugmentationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        mask_ratio = trial.suggest_float("mask_ratio", hyperparams_config["mask_ratio"][0], hyperparams_config["mask_ratio"][1])
        jitter_sigma = trial.suggest_float("jitter_sigma", hyperparams_config["jitter_sigma"][0], hyperparams_config["jitter_sigma"][1], log=True)

        aug_params = AugmentationParams(mask_ratio, jitter_sigma)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])

        train_loader = create_loader(self.data, window_size, batch_size=64)

        opt_params = OptimizationParams(1e-3, 64)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("aug_params", aug_params.__dict__)

        return score
    
study_aug = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="augmentation_stage",
    load_if_exists=True
)
study_aug.optimize(AugmentationStageObjective(data, device, 
                                                     {
      **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"]
}
), n_trials=50)

[I 2026-02-27 22:12:10,765] A new study created in RDB with name: augmentation_stage
[I 2026-02-27 22:12:28,005] Trial 0 finished with value: 0.10942956160620576 and parameters: {'mask_ratio': 0.2857537118458853, 'jitter_sigma': 0.029130636108840445}. Best is trial 0 with value: 0.10942956160620576.
[I 2026-02-27 22:12:44,793] Trial 1 finished with value: 0.10141577823095138 and parameters: {'mask_ratio': 0.19045612026580555, 'jitter_sigma': 0.00793790567271901}. Best is trial 0 with value: 0.10942956160620576.
[I 2026-02-27 22:13:01,610] Trial 2 finished with value: 0.12030535725413294 and parameters: {'mask_ratio': 0.24846365142893945, 'jitter_sigma': 0.029822553387346386}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:13:18,560] Trial 3 finished with value: 0.09797382982022795 and parameters: {'mask_ratio': 0.43428330423072564, 'jitter_sigma': 0.007993878054723123}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:13:35,727] Trial 4 finished with value: 0.1093196596668079 and parameters: {'mask_ratio': 0.16531424239605894, 'jitter_sigma': 0.01967039133072094}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:13:52,759] Trial 5 finished with value: 0.1118994826721108 and parameters: {'mask_ratio': 0.2603186820231675, 'jitter_sigma': 0.01632366181300472}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:14:09,748] Trial 6 finished with value: 0.0984029346494405 and parameters: {'mask_ratio': 0.10299237084367757, 'jitter_sigma': 0.013593600769457054}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:14:26,618] Trial 7 finished with value: 0.09780741669470183 and parameters: {'mask_ratio': 0.18485397385266444, 'jitter_sigma': 0.006265476070089022}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:14:43,625] Trial 8 finished with value: 0.09432685169022215 and parameters: {'mask_ratio': 0.3307041905482531, 'jitter_sigma': 0.006126767186872466}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:15:00,878] Trial 9 finished with value: 0.10039495015021394 and parameters: {'mask_ratio': 0.17486397359587189, 'jitter_sigma': 0.043506238701268816}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:15:18,333] Trial 10 finished with value: 0.10709370757916137 and parameters: {'mask_ratio': 0.498975146543739, 'jitter_sigma': 0.046428593866268825}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:15:35,887] Trial 11 finished with value: 0.1013488790013044 and parameters: {'mask_ratio': 0.2888541211715241, 'jitter_sigma': 0.01649994128935984}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:15:53,459] Trial 12 finished with value: 0.10556346971950559 and parameters: {'mask_ratio': 0.3443268665868863, 'jitter_sigma': 0.02697075769593105}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:16:10,984] Trial 13 finished with value: 0.10747039620598009 and parameters: {'mask_ratio': 0.2511252725185801, 'jitter_sigma': 0.012492582370431132}. Best is trial 2 with value: 0.12030535725413294.
[I 2026-02-27 22:16:28,472] Trial 14 finished with value: 0.12778021398987893 and parameters: {'mask_ratio': 0.3669917285446426, 'jitter_sigma': 0.0289060797385181}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:16:45,914] Trial 15 finished with value: 0.10434896886414835 and parameters: {'mask_ratio': 0.38255214155132666, 'jitter_sigma': 0.03183910588814567}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:17:03,313] Trial 16 finished with value: 0.09067715171296853 and parameters: {'mask_ratio': 0.4046012163437425, 'jitter_sigma': 0.023153185009042124}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:17:20,668] Trial 17 finished with value: 0.09499999847208651 and parameters: {'mask_ratio': 0.459183888199905, 'jitter_sigma': 0.03544586491738992}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:17:37,997] Trial 18 finished with value: 0.10384268931445018 and parameters: {'mask_ratio': 0.3482872508239743, 'jitter_sigma': 0.022322173726899194}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:17:55,313] Trial 19 finished with value: 0.12047655533371193 and parameters: {'mask_ratio': 0.23127114462104867, 'jitter_sigma': 0.03726242432725091}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:18:12,602] Trial 20 finished with value: 0.12423240790067491 and parameters: {'mask_ratio': 0.21727134427426378, 'jitter_sigma': 0.03599862749738306}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:18:29,895] Trial 21 finished with value: 0.12340026516191571 and parameters: {'mask_ratio': 0.2301792118848096, 'jitter_sigma': 0.039382572585392114}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:18:47,187] Trial 22 finished with value: 0.10234933665861257 and parameters: {'mask_ratio': 0.13406902910193808, 'jitter_sigma': 0.04891845829802314}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:19:04,467] Trial 23 finished with value: 0.10524071087937725 and parameters: {'mask_ratio': 0.21354524938556813, 'jitter_sigma': 0.04068897596763029}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:19:21,754] Trial 24 finished with value: 0.10091942732492265 and parameters: {'mask_ratio': 0.3117191319329248, 'jitter_sigma': 0.025180293010142078}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:19:39,053] Trial 25 finished with value: 0.09934706189639886 and parameters: {'mask_ratio': 0.3712537905527357, 'jitter_sigma': 0.036062239882454855}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:19:56,354] Trial 26 finished with value: 0.1082234431837491 and parameters: {'mask_ratio': 0.2052145664813418, 'jitter_sigma': 0.02090901471803114}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:20:13,658] Trial 27 finished with value: 0.1119766743420394 and parameters: {'mask_ratio': 0.1435327242539327, 'jitter_sigma': 0.03349317402896415}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:20:30,973] Trial 28 finished with value: 0.12594318121308812 and parameters: {'mask_ratio': 0.27015063589029964, 'jitter_sigma': 0.04001036838114361}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:20:48,297] Trial 29 finished with value: 0.12192139125931745 and parameters: {'mask_ratio': 0.2762409836301595, 'jitter_sigma': 0.02749189210129951}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:21:05,523] Trial 30 finished with value: 0.10706849654804917 and parameters: {'mask_ratio': 0.3081275484493273, 'jitter_sigma': 0.018785639370132286}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:21:22,766] Trial 31 finished with value: 0.11001739985889436 and parameters: {'mask_ratio': 0.22836569991347283, 'jitter_sigma': 0.04120627076158941}. Best is trial 14 with value: 0.12778021398987893.
[I 2026-02-27 22:21:40,062] Trial 32 finished with value: 0.1314640650920319 and parameters: {'mask_ratio': 0.2937417773959797, 'jitter_sigma': 0.029839790317762568}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:21:57,329] Trial 33 finished with value: 0.11000388292210916 and parameters: {'mask_ratio': 0.2815337094631935, 'jitter_sigma': 0.032060753930947816}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:22:14,582] Trial 34 finished with value: 0.12257218456275643 and parameters: {'mask_ratio': 0.32263609013283273, 'jitter_sigma': 0.02979941408269328}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:22:31,865] Trial 35 finished with value: 0.08672487158045228 and parameters: {'mask_ratio': 0.37016489055357854, 'jitter_sigma': 0.024298642320612858}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:22:49,126] Trial 36 finished with value: 0.10701867036872315 and parameters: {'mask_ratio': 0.26127830107006733, 'jitter_sigma': 0.048764639332355225}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:23:06,414] Trial 37 finished with value: 0.09328593098618443 and parameters: {'mask_ratio': 0.40289795324183614, 'jitter_sigma': 0.00906530786307106}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:23:23,702] Trial 38 finished with value: 0.11288048455265187 and parameters: {'mask_ratio': 0.29780129411304573, 'jitter_sigma': 0.026184186210088233}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:23:41,072] Trial 39 finished with value: 0.12217436181771835 and parameters: {'mask_ratio': 0.2665697291584235, 'jitter_sigma': 0.030160826486519705}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:23:58,434] Trial 40 finished with value: 0.10666666763934785 and parameters: {'mask_ratio': 0.1983881337996819, 'jitter_sigma': 0.012109103589807109}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:24:15,844] Trial 41 finished with value: 0.12096705694154408 and parameters: {'mask_ratio': 0.23408826082456277, 'jitter_sigma': 0.03811848403050767}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:24:33,269] Trial 42 finished with value: 0.10862072318350191 and parameters: {'mask_ratio': 0.155708619567159, 'jitter_sigma': 0.04224579858192536}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:24:50,697] Trial 43 finished with value: 0.11255417897770836 and parameters: {'mask_ratio': 0.24315064985820622, 'jitter_sigma': 0.03351372774638193}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:25:08,121] Trial 44 finished with value: 0.10445853358977741 and parameters: {'mask_ratio': 0.21177750006783627, 'jitter_sigma': 0.005198772347651455}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:25:25,620] Trial 45 finished with value: 0.1256683415938441 and parameters: {'mask_ratio': 0.18499365387997302, 'jitter_sigma': 0.04404286637029058}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:25:43,284] Trial 46 finished with value: 0.12160923720423278 and parameters: {'mask_ratio': 0.17571028632709784, 'jitter_sigma': 0.0461857635091999}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:26:00,833] Trial 47 finished with value: 0.09822551877673869 and parameters: {'mask_ratio': 0.11969728615597941, 'jitter_sigma': 0.018186552225441754}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:26:18,316] Trial 48 finished with value: 0.11727189977313557 and parameters: {'mask_ratio': 0.34685244728229436, 'jitter_sigma': 0.02885787292561668}. Best is trial 32 with value: 0.1314640650920319.
[I 2026-02-27 22:26:35,798] Trial 49 finished with value: 0.13193062154188728 and parameters: {'mask_ratio': 0.4379409890039726, 'jitter_sigma': 0.045869891350296864}. Best is trial 49 with value: 0.13193062154188728.

In [44]:
# Optimization stage:

# learning_rate = trial.suggest_float("learning_rate", 1e-4, 3e-3, log=True)
# batch_size = trial.suggest_categorical("batch_size", [32, 64, 128])

class OptimizationStageObjective(BaseTS2VecObjective):
    
    def __call__(self, trial):

        learning_rate = trial.suggest_float("learning_rate", hyperparams_config["learning_rate"][0], hyperparams_config["learning_rate"][1], log=True)
        batch_size = trial.suggest_categorical("batch_size", hyperparams_config["batch_size"])

        opt_params = OptimizationParams(learning_rate, batch_size)

        window_size = self.fixed_params["window_size"]
        arch_params = ArchitectureParams(self.fixed_params["hidden_dim"], self.fixed_params["num_layers"])
        contrastive_params = ContrastiveParams(self.fixed_params["temperature"], self.fixed_params["exclusion_radius"])
        aug_params = AugmentationParams(self.fixed_params["mask_ratio"], self.fixed_params["jitter_sigma"])

        train_loader = create_loader(self.data, window_size, batch_size)

        model = self.build_model(arch_params)

        self.train_model(model, train_loader, contrastive_params, aug_params, opt_params)

        score = self.compute_score(model)

        trial.set_user_attr("opt_params", opt_params.__dict__)

        return score
    
study_opt = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(),
    storage="sqlite:///ts2vec_hpo.db",
    study_name="optimization_stage",
    load_if_exists=True
)
study_opt.optimize(OptimizationStageObjective(data, device,
                                                     {
  **study_window.best_trial.user_attrs["window_params"],
    **study_arch.best_trial.user_attrs["arch_params"],
    **study_contrastive.best_trial.user_attrs["contrastive_params"],
    **study_aug.best_trial.user_attrs["aug_params"]
}), n_trials=50)

[I 2026-02-27 22:28:42,627] A new study created in RDB with name: optimization_stage

[I 2026-02-27 22:28:52,277] Trial 0 finished with value: 0.13562347112467787 and parameters: {'learning_rate': 0.00016014997535220753, 'batch_size': 32}. Best is trial 0 with value: 0.13562347112467787.
[I 2026-02-27 22:29:26,347] Trial 1 finished with value: 0.1357538896477507 and parameters: {'learning_rate': 0.000384636048571105, 'batch_size': 128}. Best is trial 1 with value: 0.1357538896477507.
[I 2026-02-27 22:30:00,437] Trial 2 finished with value: 0.13921666219515794 and parameters: {'learning_rate': 0.0003866680481593282, 'batch_size': 128}. Best is trial 2 with value: 0.13921666219515794.
[I 2026-02-27 22:30:10,163] Trial 3 finished with value: 0.10568016816002579 and parameters: {'learning_rate': 0.0005916444986841068, 'batch_size': 32}. Best is trial 2 with value: 0.13921666219515794.
[I 2026-02-27 22:30:19,712] Trial 4 finished with value: 0.10484409157429442 and parameters: {'learning_rate': 0.0012211065918293872, 'batch_size': 32}. Best is trial 2 with value: 0.13921666219515794.
[I 2026-02-27 22:30:29,206] Trial 5 finished with value: 0.13346670350341483 and parameters: {'learning_rate': 0.00013589089862606693, 'batch_size': 32}. Best is trial 2 with value: 0.13921666219515794.
[I 2026-02-27 22:30:46,452] Trial 6 finished with value: 0.1453942074437251 and parameters: {'learning_rate': 0.00023386853277091804, 'batch_size': 64}. Best is trial 6 with value: 0.1453942074437251.
[I 2026-02-27 22:31:23,339] Trial 7 finished with value: 0.146354803577474 and parameters: {'learning_rate': 0.00017552906351199108, 'batch_size': 128}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:31:43,064] Trial 8 finished with value: 0.1109696058202676 and parameters: {'learning_rate': 0.0006204788351428342, 'batch_size': 64}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:32:22,563] Trial 9 finished with value: 0.1203217656702329 and parameters: {'learning_rate': 0.0004530106327385807, 'batch_size': 128}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:33:00,512] Trial 10 finished with value: 0.07299245841054414 and parameters: {'learning_rate': 0.002597749935956855, 'batch_size': 128}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:33:19,065] Trial 11 finished with value: 0.14509286914097708 and parameters: {'learning_rate': 0.00021166570455919838, 'batch_size': 64}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:33:37,268] Trial 12 finished with value: 0.12693086663701025 and parameters: {'learning_rate': 0.00024314757920585516, 'batch_size': 64}. Best is trial 7 with value: 0.146354803577474.
[I 2026-02-27 22:33:55,259] Trial 13 finished with value: 0.1968374894015421 and parameters: {'learning_rate': 0.00011624440419822255, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:34:30,644] Trial 14 finished with value: 0.16240344048739475 and parameters: {'learning_rate': 0.00010226732012427177, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:34:48,449] Trial 15 finished with value: 0.1551445628093283 and parameters: {'learning_rate': 0.00010711653557770238, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:35:23,473] Trial 16 finished with value: 0.15976352722266363 and parameters: {'learning_rate': 0.00010111830457306274, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:35:41,190] Trial 17 finished with value: 0.09939281148359003 and parameters: {'learning_rate': 0.001303586581612049, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:36:16,083] Trial 18 finished with value: 0.13728952728245358 and parameters: {'learning_rate': 0.0002955736322936775, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:36:33,756] Trial 19 finished with value: 0.11494435321179997 and parameters: {'learning_rate': 0.0008567922062117569, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:37:08,640] Trial 20 finished with value: 0.16839308921713203 and parameters: {'learning_rate': 0.00012894533751932525, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:37:43,355] Trial 21 finished with value: 0.1786262547566665 and parameters: {'learning_rate': 0.00013308680920212833, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:38:18,031] Trial 22 finished with value: 0.16170713790011748 and parameters: {'learning_rate': 0.00014911682911814033, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:38:52,670] Trial 23 finished with value: 0.16490758988191168 and parameters: {'learning_rate': 0.00013169704912005832, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:39:27,877] Trial 24 finished with value: 0.13836941243054635 and parameters: {'learning_rate': 0.0002009324253097847, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:39:45,511] Trial 25 finished with value: 0.1147182453463561 and parameters: {'learning_rate': 0.0002769549765487025, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:40:20,587] Trial 26 finished with value: 0.19629884835654998 and parameters: {'learning_rate': 0.00012882247590071836, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:40:55,141] Trial 27 finished with value: 0.1510892989897903 and parameters: {'learning_rate': 0.0003339061609382534, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:41:04,865] Trial 28 finished with value: 0.14253316295968166 and parameters: {'learning_rate': 0.00017366965018408183, 'batch_size': 32}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:41:22,459] Trial 29 finished with value: 0.16034286974682277 and parameters: {'learning_rate': 0.00015377001134156472, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:41:32,116] Trial 30 finished with value: 0.13271142647557999 and parameters: {'learning_rate': 0.00018417281631110435, 'batch_size': 32}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:42:07,054] Trial 31 finished with value: 0.17009172052072918 and parameters: {'learning_rate': 0.00012288519814074842, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:42:41,902] Trial 32 finished with value: 0.16298841538942954 and parameters: {'learning_rate': 0.0001273449763523742, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:43:16,496] Trial 33 finished with value: 0.17444144324134914 and parameters: {'learning_rate': 0.00011718475869637518, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:43:51,063] Trial 34 finished with value: 0.16815343399592508 and parameters: {'learning_rate': 0.00015981205561625003, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:44:25,619] Trial 35 finished with value: 0.14752454248635394 and parameters: {'learning_rate': 0.0001172937767611549, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:45:00,294] Trial 36 finished with value: 0.086554834820318 and parameters: {'learning_rate': 0.0024714038093847073, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:45:10,167] Trial 37 finished with value: 0.13129680581648884 and parameters: {'learning_rate': 0.0002427526436584073, 'batch_size': 32}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:45:44,970] Trial 38 finished with value: 0.16805213143739584 and parameters: {'learning_rate': 0.00015265761218040936, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:46:02,583] Trial 39 finished with value: 0.13380737968073964 and parameters: {'learning_rate': 0.0003694044139852499, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:46:12,264] Trial 40 finished with value: 0.1613242680397452 and parameters: {'learning_rate': 0.00019724482984668734, 'batch_size': 32}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:46:47,397] Trial 41 finished with value: 0.17756667654949787 and parameters: {'learning_rate': 0.000119940345713867, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:47:21,990] Trial 42 finished with value: 0.1826416362417409 and parameters: {'learning_rate': 0.00011389403338314968, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:47:56,759] Trial 43 finished with value: 0.17849029105819003 and parameters: {'learning_rate': 0.00014181630361456877, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:48:31,830] Trial 44 finished with value: 0.1723685282007802 and parameters: {'learning_rate': 0.00014382081640609937, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:49:06,552] Trial 45 finished with value: 0.14034380715625472 and parameters: {'learning_rate': 0.00022617648330423184, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:49:41,194] Trial 46 finished with value: 0.13456465360344627 and parameters: {'learning_rate': 0.00045217343903819333, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:49:58,829] Trial 47 finished with value: 0.16584592669851883 and parameters: {'learning_rate': 0.00010178472483023983, 'batch_size': 64}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:50:34,390] Trial 48 finished with value: 0.17339063745203653 and parameters: {'learning_rate': 0.0001750469532059778, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.
[I 2026-02-27 22:51:09,047] Trial 49 finished with value: 0.10665586762257906 and parameters: {'learning_rate': 0.0006517011885751468, 'batch_size': 128}. Best is trial 13 with value: 0.1968374894015421.

In [ ]:
from datetime import datetime

class TS2VecHyperparameterPipeline:
    def __init__(self, data, device, mode="long_term"):
        self.data = data
        self.device = device
        self.results = {}
        self.mode = mode  # "long_term" or "short_term"

    def _run_stage(self, name, objective_cls, fixed_params, n_trials, result_key, attr_key):
        study = optuna.create_study(
            direction="maximize",
            sampler=optuna.samplers.TPESampler(),
            storage="sqlite:///ts2vec_hpo.db",
            study_name=f"{name}_stage_{self.mode}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            load_if_exists=True,
        )
        study.optimize(objective_cls(self.data, self.device, fixed_params), n_trials=n_trials)
        self.results[result_key] = study.best_trial.user_attrs[attr_key]

    def run(self):
        self._run_stage(
            "window",
            WindowStageObjective,
            {},
            n_trials=7,
            result_key="window",
            attr_key="window_params",
        )
        self._run_stage(
            "arch",
            ArchitectureStageObjective,
            self.results["window"],
            n_trials=30,
            result_key="architecture",
            attr_key="arch_params",
        )
        self._run_stage(
            "contrastive",
            ContrastiveStageObjective,
            {**self.results["window"], **self.results["architecture"]},
            n_trials=50,
            result_key="contrastive",
            attr_key="contrastive_params",
        )
        self._run_stage(
            "augmentation",
            AugmentationStageObjective,
            {**self.results["window"], **self.results["architecture"], **self.results["contrastive"]},
            n_trials=50,
            result_key="augmentation",
            attr_key="aug_params",
        )
        self._run_stage(
            "optimization",
            OptimizationStageObjective,
            {
                **self.results["window"],
                **self.results["architecture"],
                **self.results["contrastive"],
                **self.results["augmentation"],
            },
            n_trials=50,
            result_key="optimization",
            attr_key="opt_params",
        )
        return self.results

# Run the pipeline
pipeline = TS2VecHyperparameterPipeline(data, device, mode="long_term")
final_results = pipeline.run()
print(final_results)

In [45]:
# list all the best parameters from each stage
param_summary = {
    "window": study_window.best_trial.user_attrs["window_params"],
    "architecture": study_arch.best_trial.user_attrs["arch_params"],
    "contrastive": study_contrastive.best_trial.user_attrs["contrastive_params"],
    "augmentation": study_aug.best_trial.user_attrs["aug_params"],
    "optimization": study_opt.best_trial.user_attrs["opt_params"]
}

```json
{'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 4},
 'contrastive': {'temperature': 0.10901392823581604, 'exclusion_radius': 18},
 'augmentation': {'mask_ratio': 0.10112014206194599,
  'jitter_sigma': 0.019884546877356246},
 'optimization': {'learning_rate': 0.0012543308801674451, 'batch_size': 64}}
```
```json
{'window': 60,
 'architecture': {'hidden_dim': 128, 'num_layers': 4},
 'contrastive': {'temperature': 0.09418251159949012, 'exclusion_radius': 3},
 'augmentation': {'mask_ratio': 0.1153883102823196,
  'jitter_sigma': 0.006324426296094188},
 'optimization': {'learning_rate': 0.0017009936483370917, 'batch_size': 32}}
```

In [33]:
param_summary

{'window': {'window_size': 40},
 'architecture': {'hidden_dim': 128, 'num_layers': 3},
 'contrastive': {'temperature': 0.05865611450479419, 'exclusion_radius': 5},
 'augmentation': {'mask_ratio': 0.11860240054087702,
  'jitter_sigma': 0.028089550039277756},
 'optimization': {'learning_rate': 0.00015072787810725861, 'batch_size': 32}}

In [46]:
param_summary

{'window': {'window_size': 180},
 'architecture': {'hidden_dim': 256, 'num_layers': 3},
 'contrastive': {'temperature': 0.06295392144086782, 'exclusion_radius': 19},
 'augmentation': {'mask_ratio': 0.4379409890039726,
  'jitter_sigma': 0.045869891350296864},
 'optimization': {'learning_rate': 0.00011624440419822255, 'batch_size': 64}}